<#
|==============================================================================>|
   AP-Compiler by APoorv Verma [AP] on 4/21/2014
|==============================================================================>|
    $) Compiles AP-Programs Independent of the AP-Modules file
    $) Reads And Calculates all the Modules needed!
    $) Adds code with comment in a neat BASE64 Code
    $) Has a blacklisting system
    $) Code layout detection
    $) Inject Point Detection
    $) AP-Compiler Forced Commands (ap-compiler: Write-AP,AP-Require)
    $) AST Based Function / Alias / Class Resolution (including forced commands)
    $) Remove Old Compiler Code
    $) AP-Compiler Debug Mode
    $) Highly performant lexical scanner
    $) Mini AP-Console Shim for AP-Console Functions
    $) Detailed Logging, verbose debugging
|==============================================================================>|
#>
[CmdletBinding(DefaultParameterSetName = 'Compile')]
param(
    [Parameter(Mandatory=$True, ParameterSetName='Compile', Position = 0)]
    [Parameter(Mandatory=$True, ParameterSetName='Uncompile', Position = 0)]
    [String]$File,
    [Parameter(ParameterSetName='Compile', Position = 1)][String]$OutputFolder = '.',
    [Parameter(ParameterSetName='Compile')][switch]$OverwriteSrc,
    [Parameter(ParameterSetName='Compile')][switch]$ForceLinearLayout,
    [Switch]$Dbg,
    [Parameter(ParameterSetName='Uncompile')][Alias('Uncompile')][Switch]$Strip,
    [Parameter(ParameterSetName='Compile')][Switch]$PassThru
)
# =======================================START=OF=COMPILER================================================================|
#    The Following Code was added by AP-Compiler 1.6 (APC: 1.3) To Make this program independent of AP-Core Engine
#    GitHub: https://github.com/avdaredevil/AP-Compiler
# ========================================================================================================================|
$Script:PSHell=$(if($PSHell){$PSHell}elseif($PSScriptRoot){$PSScriptRoot}else{"."});
if($AP_CONSOLE.mode -ne 'main' -or $AP_CONSOLE.customFlags.runAsCompiled) {
    $Script:AP_CONSOLE = [PsCustomObject]@{version=[version]'1.3'; mode = 'shim'; customFlags = @{}}
    function B64 {param([Parameter(ValueFromPipeline=$true)][String]$Text, [ValidateSet("UTF8","Unicode")][String]$Encoding = "UTF8")     [System.Text.Encoding]::$Encoding.GetString([System.Convert]::FromBase64String($Text))}
    # This syntax is to prevent AV's from misclassifying this as anything but innocuous
    & (Get-Alias iex) (B64 "ZnVuY3Rpb24gV3JpdGUtQVAgew0KICAgIFtDbWRsZXRCaW5kaW5nKCldDQogICAgcGFyYW0oW1BhcmFtZXRlcihWYWx1ZUZyb21QaXBlbGluZT0xLCBNYW5kYXRvcnk9MSldJFRleHQsW1N3aXRjaF0kTm9TaWduLFtTd2l0Y2hdJFBsYWluVGV4dCxbVmFsaWRhdGVTZXQoIkNlbnRlciIsIlJpZ2h0IiwiTGVmdCIpXVtTdHJpbmddJEFsaWduPSdMZWZ0JyxbU3dpdGNoXSRQYXNzVGhydSkNCiAgICBiZWdpbiB7JFRUID0gQCgpfQ0KICAgIFByb2Nlc3MgeyRUVCArPSAsJFRleHR9DQogICAgRU5EIHsNCiAgICAgICAgJEJsdWUgPSAkKGlmICgkQVBfQ09OU09MRS5jdXN0b21GbGFncy5sZWdhY3lDb2xvcnMpezN9ZWxzZXsnQmx1ZSd9KQ0KICAgICAgICBpZiAoJFRULmNvdW50IC1lcSAxKSB7JFRUID0gJFRUWzBdfTskVGV4dCA9ICRUVA0KICAgICAgICBpZiAoJHRleHQuY291bnQgLWd0IDEgLW9yICR0ZXh0LkdldFR5cGUoKS5OYW1lIC1tYXRjaCAiXFtcXSQiKSB7DQogICAgICAgICAgICByZXR1cm4gJFRleHQgfCAlIHsNCiAgICAgICAgICAgICAgICBXcml0ZS1BUCAkXyAtTm9TaWduOiROb1NpZ24gLVBsYWluVGV4dDokUGxhaW5UZXh0IC1BbGlnbiAkQWxpZ24gLVBhc3NUaHJ1OiRQYXNzVGhydQ0KICAgICAgICAgICAgfQ0KICAgICAgICB9DQogICAgICAgIGlmICghJHRleHQgLW9yICR0ZXh0IC1ub3RtYXRjaCAiKD9zbWkpXigoPzxOTkw+eCl8KD88TlM+bnM/KSl7MCwyfSg/PHQ+XD4qKSg/PHM+W1wrXC1cIVwqXCNcQF9dKSg/PHc+LiopIikge3JldHVybiBBbGlnbi1UZXh0ICRUZXh0IC1BbGlnbiAkQWxpZ24gfCBXcml0ZS1Ib3N0fQ0KICAgICAgICAkdGIgID0gIiAgICAiKiRNYXRjaGVzLnQubGVuZ3RoDQogICAgICAgICRDb2wgPSBAeycrJz0nMic7Jy0nPScxMic7JyEnPScxNCc7JyonPSRCbHVlOycjJz0nRGFya0dyYXknOydAJz0nR3JheSc7J18nPSd3aGl0ZSd9WygkU2lnbiA9ICRNYXRjaGVzLlMpXQ0KICAgICAgICBpZiAoISRDb2wpIHtUaHJvdyAiSW5jb3JyZWN0IFNpZ24gWyRTaWduXSBQYXNzZWQhIn0NCiAgICAgICAgJFNpZ24gPSAkKGlmICgkTm9TaWduIC1vciAkTWF0Y2hlcy5OUykgeyIifSBlbHNlIHsiWyRTaWduXSAifSkNCiAgICAgICAgJERhdGEgPSAiJHRiJFNpZ24kKCRNYXRjaGVzLlcpIjtpZiAoISREYXRhKSB7cmV0dXJuIFdyaXRlLUhvc3QgIiJ9DQogICAgICAgIGlmIChBUC1SZXF1aXJlICJmdW5jdGlvbjpBbGlnbi1UZXh0IiAtcGEpIHsNCiAgICAgICAgICAgICREYXRhID0gQWxpZ24tVGV4dCAtQWxpZ24gJEFsaWduICIkdGIkU2lnbiQoJE1hdGNoZXMuVykiDQogICAgICAgIH0NCiAgICAgICAgaWYgKCRQbGFpblRleHQpIHtyZXR1cm4gJERhdGF9DQogICAgICAgICREYXRhTGluZXMgPSAkRGF0YSAtc3BsaXQgImBuIg0KICAgICAgICAxLi4kRGF0YUxpbmVzLkNvdW50IHwgJSB7DQogICAgICAgICAgICAkSWR4ID0gJF8gLSAxDQogICAgICAgICAgICAkTk5MID0gISRpZHggLWFuZCAkTWF0Y2hlcy5OTkwNCiAgICAgICAgICAgIFdyaXRlLUhvc3QgLU5vTmV3TGluZTokTk5MIC1mICRDb2wgJERhdGFMaW5lc1skSWR4XQ0KICAgICAgICAgICAgaWYgKCRQYXNzVGhydSkge3JldHVybiAkRGF0YX0NCiAgICAgICAgfQ0KICAgIH0NCn0KCmZ1bmN0aW9uIFNldC1QYXRoIHsNCiAgICBbY21kbGV0YmluZGluZygpXQ0KICAgIHBhcmFtKA0KICAgICAgICBbUGFyYW1ldGVyKE1hbmRhdG9yeSA9ICR0cnVlLCBWYWx1ZUZyb21QaXBlbGluZSA9ICR0cnVlKV1bc3RyaW5nW11dJFBhdGgsDQogICAgICAgIFtzdHJpbmddJFBhdGhTZXAsDQogICAgICAgIFtzdHJpbmddJFBhdGhWYXIgPSAiUEFUSCINCiAgICApDQogICAgYmVnaW4gew0KICAgICAgICBbc3RyaW5nW11dJEZpbmFsUGF0aCA9IEAoKQ0KICAgICAgICAkUGF0aFNlcCA9IEdldC1QYXRoVmFyU2VwICRQYXRoU2VwDQogICAgfQ0KICAgIHByb2Nlc3Mgew0KICAgICAgICAkUGF0aCB8ICUgew0KICAgICAgICAgICAgJEZpbmFsUGF0aCArPSAkXw0KICAgICAgICB9DQogICAgfQ0KICAgIGVuZCB7DQogICAgICAgICRQdGggPSAkRmluYWxQYXRoIC1qb2luICRQYXRoU2VwDQogICAgICAgICRQdGggPSAoJFB0aCAtcmVwbGFjZSgiJFBhdGhTZXArIiwgJFBhdGhTZXApIC1yZXBsYWNlKCJcXCRQYXRoU2VwfFxcJCIsICRQYXRoU2VwKSkudHJpbSgkUGF0aFNlcCkNCiAgICAgICAgJFB0aCA9ICgoJFB0aCkuc3BsaXQoJFBhdGhTZXApIHwgc2VsZWN0IC11bmlxdWUpIC1qb2luICRQYXRoU2VwDQogICAgICAgIFtFbnZpcm9ubWVudF06OlNldEVudmlyb25tZW50VmFyaWFibGUoJFBhdGhWYXIsICRQdGgpDQogICAgfQ0KfQoKZnVuY3Rpb24gVGVzdC1BZG1pbmlzdHJhdG9yIHsNCiAgICBpZiAoJFBTVmVyc2lvblRhYmxlLlBsYXRmb3JtIC1lcSAiVW5peCIpIHsNCiAgICAgICAgaWYgKCQod2hvYW1pKSAtZXEgInJvb3QiKSB7DQogICAgICAgICAgICByZXR1cm4gJHRydWUNCiAgICAgICAgfQ0KICAgICAgICBlbHNlIHsNCiAgICAgICAgICAgIHJldHVybiAkZmFsc2UNCiAgICAgICAgfQ0KICAgIH0NCiAgICAjIFdpbmRvd3MNCiAgICAoTmV3LU9iamVjdCBTZWN1cml0eS5QcmluY2lwYWwuV2luZG93c1ByaW5jaXBhbCAoW1NlY3VyaXR5LlByaW5jaXBhbC5XaW5kb3dzSWRlbnRpdHldOjpHZXRDdXJyZW50KCkpKS5Jc0luUm9sZShbU2VjdXJpdHkuUHJpbmNpcGFsLldpbmRvd3NCdWlsdGluUm9sZV06OkFkbWluaXN0cmF0b3IpDQp9CgpmdW5jdGlvbiBJbnZva2UtT3JSZXR1cm4ge3BhcmFtKFtQYXJhbWV0ZXIoTWFuZGF0b3J5PSR0cnVlLCBWYWx1ZUZyb21QaXBlbGluZT0kdHJ1ZSwgUG9zaXRpb249MCldW0FsbG93TnVsbCgpXSRDb2RlLCBbUGFyYW1ldGVyKFZhbHVlRnJvbVJlbWFpbmluZ0FyZ3VtZW50cz0xKV0kX19SZXN0LCBbU3dpdGNoXSRBc1Byb2Nlc3NCbG9jaykNCg0KICAgIGlmICghKCRDb2RlIC1pcyBbU2NyaXB0QmxvY2tdKSkge3JldHVybiAkQ29kZX0NCiAgICBpZiAoISRBc1Byb2Nlc3NCbG9jaykge3JldHVybiAmICRDb2RlIEBfX1Jlc3R9DQogICAgcmV0dXJuICUgLXByb2Nlc3MgJENvZGUgLUlucHV0T2JqZWN0ICRfX1Jlc3QNCn0KCmZ1bmN0aW9uIFN0cmlwLUNvbG9yQ29kZXMgew0KICAgIFtDbWRsZXRCaW5kaW5nKCldcGFyYW0oW1BhcmFtZXRlcihWYWx1ZUZyb21QaXBlbGluZT0xKV0kU3RyKQ0KICAgIHByb2Nlc3MgeyRTdHIgfCAlIHskXyAtcmVwbGFjZSAiJChbcmVnZXhdOjplc2NhcGUoIiQoR2V0LUVzY2FwZSlbIikpXGQrKFw7XGQrKSptIiwiIn19DQp9CgpmdW5jdGlvbiBHZXQtRmlsZUVuY29kaW5nIHtwYXJhbShbUGFyYW1ldGVyKE1hbmRhdG9yeT0kVHJ1ZSldJFBhdGgpDQoNCiAgICAkYnl0ZXMgPSBbYnl0ZVtdXShHZXQtQ29udGVudCAkUGF0aCAtQXNCeXRlU3RyZWFtIC1SZWFkQ291bnQgNCAtVG90YWxDb3VudCA0KQ0KDQogICAgaWYoISRieXRlcykge3JldHVybiAndXRmOCd9DQoNCiAgICBzd2l0Y2ggLXJlZ2V4ICgnezA6eDJ9ezE6eDJ9ezI6eDJ9ezM6eDJ9JyAtZiAkYnl0ZXNbMF0sJGJ5dGVzWzFdLCRieXRlc1syXSwkYnl0ZXNbM10pIHsNCiAgICAgICAgJ15lZmJiYmYnICAge3JldHVybiAndXRmOCd9DQogICAgICAgICdeMmIyZjc2JyAgIHtyZXR1cm4gJ3V0ZjcnfQ0KICAgICAgICAnXmZmZmUnICAgICB7cmV0dXJuICd1bmljb2RlJ30NCiAgICAgICAgJ15mZWZmJyAgICAge3JldHVybiAnYmlnZW5kaWFudW5pY29kZSd9DQogICAgICAgICdeMDAwMGZlZmYnIHtyZXR1cm4gJ3V0ZjMyJ30NCiAgICAgICAgZGVmYXVsdCAgICAge3JldHVybiAnYXNjaWknfQ0KICAgIH0NCn0KCmZ1bmN0aW9uIEdldC1XaGVyZSB7DQogICAgW0NtZGxldEJpbmRpbmcoRGVmYXVsdFBhcmFtZXRlclNldE5hbWU9Ik5vcm1hbCIpXQ0KICAgIHBhcmFtKA0KICAgICAgICBbUGFyYW1ldGVyKE1hbmRhdG9yeT0kdHJ1ZSwgUG9zaXRpb249MCldW3N0cmluZ10kRmlsZSwNCiAgICAgICAgW1N3aXRjaF0kQWxsLA0KICAgICAgICBbUGFyYW1ldGVyKFBhcmFtZXRlclNldE5hbWU9J05vcm1hbCcpXVtQYXJhbWV0ZXIoUGFyYW1ldGVyU2V0TmFtZT0nU2NhbicpXVtTd2l0Y2hdJE1hbnVhbFNjYW4sDQogICAgICAgIFtQYXJhbWV0ZXIoUGFyYW1ldGVyU2V0TmFtZT0nU2NhbicpXVtTd2l0Y2hdJERiZywNCiAgICAgICAgW1BhcmFtZXRlcihQYXJhbWV0ZXJTZXROYW1lPSdTY2FuJyldW3N0cmluZ10kUGF0aFZhciA9ICJQQVRIIg0KICAgICkNCiAgICAkSXNWZXJib3NlID0gJERiZyAtb3IgJFBTQ21kbGV0Lk15SW52b2NhdGlvbi5Cb3VuZFBhcmFtZXRlcnMuVmVyYm9zZSAtb3IgJFBTQ21kbGV0Lk15SW52b2NhdGlvbi5Cb3VuZFBhcmFtZXRlcnMuRGVidWcNCiAgICAkV2hlcmVCaW5FeGlzdHMgPSBHZXQtQ29tbWFuZCAid2hlcmUiIC1lYSBTaWxlbnRseUNvbnRpbnVlDQogICAgJElzVW5peCA9ICRQU1ZlcnNpb25UYWJsZS5QbGF0Zm9ybSAtZXEgIlVuaXgiDQogICAgaWYgKCRGaWxlIC1lcSAid2hlcmUiIC1vciAkRmlsZSAtZXEgIndoZXJlLmV4ZSIpIHtyZXR1cm4gJFdoZXJlQmluRXhpc3RzfQ0KICAgIGlmICgkV2hlcmVCaW5FeGlzdHMgLWFuZCAhJE1hbnVhbFNjYW4pIHsNCiAgICAgICAgJE91dD0kbnVsbA0KICAgICAgICBpZiAoJElzVW5peCkgew0KICAgICAgICAgICAgJE91dCA9IHdoaWNoICRmaWxlIDI+JG51bGwNCiAgICAgICAgfSBlbHNlIHskT3V0ID0gd2hlcmUuZXhlICRmaWxlIDI+JG51bGx9DQoNCiAgICAgICAgaWYgKCEkT3V0KSB7cmV0dXJufQ0KICAgICAgICBpZiAoJEFsbCkge3JldHVybiAkT3V0fQ0KICAgICAgICByZXR1cm4gQCgkT3V0KVswXQ0KICAgIH0NCiAgICBmb3JlYWNoICgkRm9sZGVyIGluIChHZXQtUGF0aCAtUGF0aFZhciAkUGF0aFZhcikpIHsNCiAgICAgICAgaWYgKCRJc1VuaXgpIHsNCiAgICAgICAgICAgICRMb29rdXAgPSAiJEZvbGRlci8kRmlsZSINCiAgICAgICAgICAgIGlmICgkSXNWZXJib3NlKSB7V3JpdGUtQVAgIipDaGVja2luZyBbJExvb2t1cF0ifQ0KICAgICAgICAgICAgaWYgKCEoVGVzdC1QYXRoIC1QYXRoVHlwZSBMZWFmICRMb29rdXApKSB7Y29udGludWV9DQogICAgICAgICAgICBSZXNvbHZlLVBhdGggJExvb2t1cCB8ICUgUGF0aA0KICAgICAgICAgICAgaWYgKCEkQWxsKSB7cmV0dXJufQ0KICAgICAgICB9IGVsc2Ugew0KICAgICAgICAgICAgZm9yZWFjaCAoJEV4dGVuc2lvbiBpbiAoR2V0LVBhdGggLVBhdGhWYXIgUEFUSEVYVCkpIHsNCiAgICAgICAgICAgICAgICAkTG9va3VwID0gIiRGb2xkZXIvJEZpbGUkRXh0ZW5zaW9uIg0KICAgICAgICAgICAgICAgIGlmICgkSXNWZXJib3NlKSB7V3JpdGUtQVAgIipDaGVja2luZyBbJExvb2t1cF0ifQ0KICAgICAgICAgICAgICAgIGlmICghKFRlc3QtUGF0aCAtUGF0aFR5cGUgTGVhZiAkTG9va3VwKSkge2NvbnRpbnVlfQ0KICAgICAgICAgICAgICAgIFJlc29sdmUtUGF0aCAkTG9va3VwIHwgJSBQYXRoDQogICAgICAgICAgICAgICAgaWYgKCEkQWxsKSB7cmV0dXJufQ0KICAgICAgICAgICAgfQ0KICAgICAgICB9DQogICAgfQ0KfQoKZnVuY3Rpb24gQWxpZ24tVGV4dCB7DQogICAgW0NtZGxldEJpbmRpbmcoKV0NCiAgICBbT3V0cHV0VHlwZShbU3RyaW5nXSwgW0hhc2h0YWJsZV0pXQ0KICAgIHBhcmFtKA0KICAgICAgICBbUGFyYW1ldGVyKE1hbmRhdG9yeT0xLCBWYWx1ZUZyb21QaXBlbGluZT0xKV1bQWxsb3dFbXB0eVN0cmluZygpXVtTdHJpbmdbXV0kVGV4dCwNCiAgICAgICAgW3N3aXRjaF0kQ29sb3JDb2Rlc0Rpc2NyZXRlUGVyTGluZSwNCiAgICAgICAgW3N3aXRjaF0kUG9yY2VsYWluLA0KICAgICAgICAjIFRoaXMgY2FuIGJlIFtpbnRdIG9yIFtzY3JpcHRibG9ja10NCiAgICAgICAgJENvbnN0cmFpblRvV2lkdGgsDQogICAgICAgIFtWYWxpZGF0ZVNldCgiQ2VudGVyIiwiUmlnaHQiLCJMZWZ0IildW1N0cmluZ10kQWxpZ249J0NlbnRlcicNCiAgICApDQogICAgYmVnaW4gew0KICAgICAgICAkaXNWZXJib3NlID0gJFBTQ21kbGV0Lk15SW52b2NhdGlvbi5Cb3VuZFBhcmFtZXRlcnMuVmVyYm9zZQ0KICAgICAgICAkRXNjYXBlQ29kZVNwbGl0dGVyID0gIiQoW3JlZ2V4XTo6ZXNjYXBlKCIkKEdldC1Fc2NhcGUpWyIpKVxkKyg/Olw7XGQrKSptIg0KICAgICAgICAkRGl2aWRlcnMgPSBAe2NodW5rID0gUHJvY2Vzcy1Vbmljb2RlICJgdXsxMTI4OH0iOyBzdHlsZSA9IFByb2Nlc3MtVW5pY29kZSAiYHV7MTIyODh9In0NCiAgICAgICAgJEZpbmFsRm9ybWF0dGVyID0gew0KICAgICAgICAgICAgcGFyYW0oJExpbmVzLCAkU3R5bGVzKQ0KICAgICAgICAgICAgaWYgKCEkUG9yY2VsYWluKSB7cmV0dXJuICRMaW5lc30NCiAgICAgICAgICAgIGlmICgkbnVsbCAtZXEgJFN0eWxlcykgeyRTdHlsZXMgPSBbUmVnZXhdOjpNYXRjaGVzKCgkTGluZXMgLWpvaW4gIiIpLCAkRXNjYXBlQ29kZVNwbGl0dGVyKS52YWx1ZX0NCiAgICAgICAgICAgIHJldHVybiBAe0xpbmVzID0gJExpbmVzOyBSdW5uaW5nU3R5bGVzID0gJFN0eWxlc30NCiAgICAgICAgfQ0KICAgIH0NCiAgICBwcm9jZXNzIHsNCiAgICAgICAgaWYgKCRBbGlnbiAtZXEgIkxlZnQiKSB7cmV0dXJuICYgJEZpbmFsRm9ybWF0dGVyICRUZXh0fQ0KICAgICAgICBpZiAoISIkVGV4dCIudHJpbSgpKSB7cmV0dXJuICRUZXh0fQ0KICAgICAgICAkV2luU2l6ZSA9ID86ICRDb25zdHJhaW5Ub1dpZHRoIHtJbnZva2UtT3JSZXR1cm4gJENvbnN0cmFpblRvV2lkdGh9IChbY29uc29sZV06OkJ1ZmZlcldpZHRoKQ0KICAgICAgICANCiAgICAgICAgJFRleHQgPSAkVGV4dCAtc3BsaXQgImByP2BuIg0KICAgICAgICBpZiAoJFRleHQuY291bnQgLWd0IDEpIHsNCiAgICAgICAgICAgICRMaW5lcyA9ICRUZXh0IHwgQWxpZ24tVGV4dCAtQWxpZ24gJEFsaWduIC1Db2xvckNvZGVzRGlzY3JldGVQZXJMaW5lOiRDb2xvckNvZGVzRGlzY3JldGVQZXJMaW5lIC1Qb3JjZWxhaW4NCiAgICAgICAgICAgIGlmICgkQ29sb3JDb2Rlc0Rpc2NyZXRlUGVyTGluZSkgew0KICAgICAgICAgICAgICAgIGZvciAoJGkgPSAxOyAkaSAtbHQgJExpbmVzLkNvdW50OyAkaSsrKSB7DQogICAgICAgICAgICAgICAgICAgICRMaW5lID0gJExpbmVzWyRpXQ0KICAgICAgICAgICAgICAgICAgICAkUHJldlN0eWxlcyArPSAkTGluZXNbJGkgLSAxXS5SdW5uaW5nU3R5bGVzDQogICAgICAgICAgICAgICAgICAgICRMaW5lLkxpbmVzID0gJExpbmUuTGluZXMgfCAlIHsiJFByZXZTdHlsZXMkXyJ9DQogICAgICAgICAgICAgICAgICAgICRMaW5lLlJ1bm5pbmdTdHlsZXMgPSAiJFByZXZTdHlsZXMkKCRMaW5lLlJ1bm5pbmdTdHlsZXMpIg0KICAgICAgICAgICAgICAgIH0NCiAgICAgICAgICAgIH0NCiAgICAgICAgICAgIHJldHVybiAmICRGaW5hbEZvcm1hdHRlciAoRmxhdHRlbiAkTGluZXMuTGluZXMpICgkTGluZXMuUnVubmluZ1N0eWxlcyAtam9pbiAiIikNCiAgICAgICAgfQ0KICAgICAgICAjIFNpbmdsZSBub24gYG4gbGluZSBwcm9jZXNzDQogICAgICAgICRDbGVhblRleHRTaXplID0gKFN0cmlwLUNvbG9yQ29kZXMgKCIiKyRUZXh0KSkuTGVuZ3RoDQoNCiAgICAgICAgIyA9PT09PT09PSBMaW5lIGlzIDwgJFdpblNpemUgPT09PT09PT09PT09PT18DQogICAgICAgIGlmICgkQ2xlYW5UZXh0U2l6ZSAtbGUgJFdpblNpemUpIHsNCiAgICAgICAgICAgIGlmICgkQWxpZ24gLWVxICJDZW50ZXIiKSB7DQogICAgICAgICAgICAgICAgcmV0dXJuICYgJEZpbmFsRm9ybWF0dGVyICgiICIqW21hdGhdOjp0cnVuY2F0ZSgoJFdpblNpemUtJENsZWFuVGV4dFNpemUpLzIpKyRUZXh0KQ0KICAgICAgICAgICAgfQ0KICAgICAgICAgICAgIyBSaWdodA0KICAgICAgICAgICAgcmV0dXJuICYgJEZpbmFsRm9ybWF0dGVyICgiICIqKCRXaW5TaXplLSRDbGVhblRleHRTaXplKSskVGV4dCkNCiAgICAgICAgfQ0KDQogICAgICAgICMgPT09PT09PT0gTGluZSBpcyA+PSAkV2luU2l6ZSA9PT09PT09PT09PT09PXwNCiAgICAgICAgIyBUcmFja2luZyBTdHlsZXMNCiAgICAgICAgJFJ1bm5pbmdTdHlsZXMgPSAiIg0KICAgICAgICAkQ3VycmxpbmUgPSBAew0KICAgICAgICAgICAgc3R5bGVkRGF0YSA9ICIiDQogICAgICAgICAgICBjb250ZW50U2l6ZSA9IDANCiAgICAgICAgICAgIGZpbmFsTGluZXMgPSBAKCkNCiAgICAgICAgICAgIG5leHQgPSB7DQogICAgICAgICAgICAgICAgIyBXcml0ZS1WZXJib3NlICIqJEludm9rIHwgTmV3IExpbmUgfCBMaW5lRGF0YTogJCgoJycrJEN1cnJsaW5lLnN0eWxlZERhdGEuTGVuZ3RoKS5QYWRMZWZ0KDMpKSINCiAgICAgICAgICAgICAgICAkQ3VycmxpbmUuZmluYWxMaW5lcyArPSAsJEN1cnJsaW5lLnN0eWxlZERhdGENCiAgICAgICAgICAgICAgICAkQ3VycmxpbmUuc3R5bGVkRGF0YSA9ICRSdW5uaW5nU3R5bGVzDQogICAgICAgICAgICAgICAgJEN1cnJsaW5lLmNvbnRlbnRTaXplID0gMA0KICAgICAgICAgICAgICAgICMgV3JpdGUtVmVyYm9zZSAiKiRJbnZvayB8IEN1cnIgVG90YWwgTGluZXM6ICQoJGN1cnJsaW5lLmZpbmFsTGluZXMuQ291bnQpIg0KICAgICAgICAgICAgfQ0KICAgICAgICB9DQogICAgICAgICRBbGxDaHVua3MgPSAkVGV4dCAtcmVwbGFjZSAiKCR7RXNjYXBlQ29kZVNwbGl0dGVyfSkrKC4qPykoPz0ke0VzY2FwZUNvZGVTcGxpdHRlcn18JCkiLCIkKCREaXZpZGVycy5jaHVuaylgJDEkKCREaXZpZGVycy5zdHlsZSlgJDIiIC1zcGxpdCAkRGl2aWRlcnMuY2h1bmsNCiAgICAgICAgaWYgKCRBbGxDaHVua3NbMF0gLW5vdGNvbnRhaW5zICREaXZpZGVycy5zdHlsZSkgeyRBbGxDaHVua3NbMF0gPSAiJCgkRGl2aWRlcnMuc3R5bGUpJCgkQWxsQ2h1bmtzWzBdKSJ9ICMgVGhlIGZpcnN0IGNodW5rIGNvdWxkIGhhdmUgbm8gc3R5bGVzDQogICAgICAgIGZvcmVhY2ggKCRDdXJyQ2h1bmsgaW4gJEFsbENodW5rcykgew0KICAgICAgICAgICAgJFN0eWxlLCRUZXh0Q2h1bmsgPSAkQ3VyckNodW5rIC1zcGxpdCAkRGl2aWRlcnMuc3R5bGUNCiAgICAgICAgICAgICRSdW5uaW5nU3R5bGVzID0gPzogJENvbG9yQ29kZXNEaXNjcmV0ZVBlckxpbmUgIiRSdW5uaW5nU3R5bGVzJFN0eWxlIiAkU3R5bGUNCiAgICAgICAgICAgICMgV3JpdGUtSG9zdCAtZiAyICgiSW5jb21pbmdTdHlsZTogJFN0eWxlIHwgUnVubmluZ1N0eWxlczogJFJ1bm5pbmdTdHlsZXMiIC1yZXBsYWNlIChbcmVnZXhdOjpFc2NhcGUoJChHZXQtRXNjYXBlKSkpLCdcZScpDQogICAgICAgICAgICAjIFdyaXRlLUhvc3QgLWYgWWVsbG93ICJUZXh0Q2h1bms6ICRUZXh0Q2h1bmsiDQogICAgICAgICAgICAkQ3VycmxpbmUuc3R5bGVkRGF0YSArPSAkUnVubmluZ1N0eWxlcw0KICAgICAgICAgICAgJFRleHRDaHVua1N0ckluZGV4ID0gMA0KICAgICAgICAgICAgIyBXcml0ZS1WZXJib3NlICIqJEludm9rIHwgVGV4dENodW5rOiAkVGV4dENodW5rIHwgQWxsQ2h1bmtzU2l6ZTogJCgoJycrJEFsbENodW5rcy5MZW5ndGgpLlBhZExlZnQoMykpIg0KICAgICAgICAgICAgd2hpbGUoJFRleHRDaHVua1N0ckluZGV4IC1sdCAkVGV4dENodW5rLkxlbmd0aCkgew0KICAgICAgICAgICAgICAgIGlmICgkaXNWZXJib3NlKSB7UGxhY2UtQnVmZmVyZWRDb250ZW50ICgiJEludm9rIHwgTGluZURhdGE6ICQoKCcnKyRDdXJybGluZS5zdHlsZWREYXRhLkxlbmd0aCkuUGFkTGVmdCgzKSkgfCBDaHVua0lkeDogJCgoJycrJFRleHRDaHVua1N0ckluZGV4KS5QYWRMZWZ0KDMpKSB8IENodW5rTGVuOiAkKCRUZXh0Q2h1bmsuTGVuZ3RoKSB8IEZpbmFsTGluZXM6ICQoJEN1cnJsaW5lLmZpbmFsTGluZXMuQ291bnQpIikgLXggMCAteSAoW0NvbnNvbGVdOjpCdWZmZXJIZWlnaHQgLSAxKSBZZWxsb3cgRGFya0dyYXl9DQogICAgICAgICAgICAgICAgJENodW5rU2l6ZSA9ICRUZXh0Q2h1bmsuTGVuZ3RoIC0gJFRleHRDaHVua1N0ckluZGV4DQogICAgICAgICAgICAgICAgV3JpdGUtVmVyYm9zZSAiKkNodW5rU2l6ZTogJENodW5rU2l6ZSB8ICQoJEN1cnJsaW5lLmNvbnRlbnRTaXplKSB8ICRXaW5TaXplIg0KICAgICAgICAgICAgICAgIGlmICgoJEN1cnJsaW5lLmNvbnRlbnRTaXplKyRDaHVua1NpemUpIC1sdCAkV2luU2l6ZSkgew0KICAgICAgICAgICAgICAgICAgICAjIElmIHRoZSBjdXJyZW50IGNodW5rIGZpdHMgaW4gdGhlIGN1cnJlbnQgbGluZQ0KICAgICAgICAgICAgICAgICAgICAkQ3VycmxpbmUuc3R5bGVkRGF0YSArPSAkVGV4dENodW5rLlN1YnN0cmluZygkVGV4dENodW5rU3RySW5kZXgpDQogICAgICAgICAgICAgICAgICAgICRDdXJybGluZS5jb250ZW50U2l6ZSArPSAkQ2h1bmtTaXplDQogICAgICAgICAgICAgICAgICAgICRUZXh0Q2h1bmtTdHJJbmRleCArPSAkQ2h1bmtTaXplDQogICAgICAgICAgICAgICAgICAgIGNvbnRpbnVlDQogICAgICAgICAgICAgICAgfQ0KICAgICAgICAgICAgICAgICMgSWYgdGhlIGN1cnJlbnQgY2h1bmsgZG9lc24ndCBmaXQgaW4gdGhlIGN1cnJlbnQgbGluZQ0KICAgICAgICAgICAgICAgICRuZXdDb250ZW50ID0gJFRleHRDaHVuay5TdWJzdHJpbmcoJFRleHRDaHVua1N0ckluZGV4LCAkV2luU2l6ZS0kQ3VycmxpbmUuY29udGVudFNpemUpDQogICAgICAgICAgICAgICAgJEN1cnJsaW5lLnN0eWxlZERhdGEgKz0gJG5ld0NvbnRlbnQNCiAgICAgICAgICAgICAgICAkQ3VycmxpbmUuY29udGVudFNpemUgKz0gJG5ld0NvbnRlbnQubGVuZ3RoDQogICAgICAgICAgICAgICAgJFRleHRDaHVua1N0ckluZGV4ICs9ICRuZXdDb250ZW50Lmxlbmd0aA0KICAgICAgICAgICAgICAgICYgJEN1cnJsaW5lLm5leHQNCiAgICAgICAgICAgIH0NCiAgICAgICAgfQ0KICAgICAgICBpZiAoJEN1cnJsaW5lLmNvbnRlbnRTaXplIC1ndCAwKSB7DQogICAgICAgICAgICBpZiAoJEN1cnJsaW5lLmNvbnRlbnRTaXplKXsNCiAgICAgICAgICAgICAgICBBbGlnbi1UZXh0IC1BbGlnbiAkQWxpZ24gLVRleHQgJEN1cnJsaW5lLnN0eWxlZERhdGEgLUNvbG9yQ29kZXNEaXNjcmV0ZVBlckxpbmU6JENvbG9yQ29kZXNEaXNjcmV0ZVBlckxpbmUgfCA/IHskX30gfCAlIHsNCiAgICAgICAgICAgICAgICAgICAgJEN1cnJsaW5lLmZpbmFsTGluZXMgKz0gLCRfDQogICAgICAgICAgICAgICAgfQ0KICAgICAgICAgICAgfSBlbHNlIHsNCiAgICAgICAgICAgICAgICAkQ3VycmxpbmUuZmluYWxMaW5lc1stMV0gKz0gJEN1cnJsaW5lLnN0eWxlZERhdGENCiAgICAgICAgICAgIH0NCiAgICAgICAgfQ0KICAgICAgICByZXR1cm4gJiAkRmluYWxGb3JtYXR0ZXIgJEN1cnJsaW5lLmZpbmFsTGluZXMgJFJ1bm5pbmdTdHlsZXMNCiAgICAgICAgcmV0dXJuICRDdXJybGluZS5maW5hbExpbmVzDQogICAgfQ0KfQoKZnVuY3Rpb24gSlMtTkNRIHtmb3JlYWNoICgkYSBpbiAkYXJncykgeyRyID0gSW52b2tlLU9yUmV0dXJuICRhO2lmICgkbnVsbCAtbmUgJHIpIHtyZXR1cm4gJHJ9fTtyZXR1cm4gJHJ9CgpmdW5jdGlvbiBQbGFjZS1CdWZmZXJlZENvbnRlbnQge3BhcmFtKCRUZXh0LCAkeCwgJHksIFtDb25zb2xlQ29sb3JdJEZvcmVncm91bmRDb2xvcj1bQ29uc29sZV06OkZvcmVncm91bmRDb2xvciwgW0NvbnNvbGVDb2xvcl0kQmFja2dyb3VuZENvbG9yPVtDb25zb2xlXTo6QmFja2dyb3VuZENvbG9yKQ0KDQogICAgaWYgKCEkVGV4dCkge3JldHVybn0NCiAgICAkY3JkID0gW01hbmFnZW1lbnQuQXV0b21hdGlvbi5Ib3N0LkNvb3JkaW5hdGVzXTo6bmV3KCR4LCR5KQ0KICAgICRiID0gJEhvc3QuVUkuUmF3VUkNCiAgICAkYXJyID0gJGIuTmV3QnVmZmVyQ2VsbEFycmF5KEAoJFRleHQpLCAkRm9yZWdyb3VuZENvbG9yLCAkQmFja2dyb3VuZENvbG9yKQ0KICAgICR4ID0gW0NvbnNvbGVdOjpCdWZmZXJXaWR0aC0xLSRUZXh0Lmxlbmd0aA0KICAgICRiLlNldEJ1ZmZlckNvbnRlbnRzKCRjcmQsICRhcnIpDQp9CgpmdW5jdGlvbiBHZXQtUGF0aCB7cGFyYW0oJG1hdGNoLCBbc3RyaW5nXSRQYXRoVmFyID0gIlBBVEgiLCBbc3RyaW5nXSRQYXRoU2VwID0gIiIpDQoNCiAgICAkUHRoID0gW0Vudmlyb25tZW50XTo6R2V0RW52aXJvbm1lbnRWYXJpYWJsZSgkUGF0aFZhcikNCiAgICAkUGF0aFNlcCA9IEdldC1QYXRoVmFyU2VwICRQYXRoU2VwDQogICAgaWYgKCEkUHRoKSB7cmV0dXJuIEAoKX0NCiAgICBTZXQtUGF0aCAkUHRoIC1QYXRoVmFyICRQYXRoVmFyIC1QYXRoU2VwICRQYXRoU2VwDQogICAgJGQgPSAoJFB0aCkuc3BsaXQoJFBhdGhTZXApDQogICAgaWYgKCRtYXRjaCkgeyRkIC1tYXRjaCAkbWF0Y2h9IGVsc2UgeyRkfQ0KfQoKZnVuY3Rpb24gSW52b2tlLVRlcm5hcnkge3BhcmFtKCRkZWNpZGVyLCAkaWZ0cnVlLCAkaWZmYWxzZSA9IHt9KQ0KDQogICAgJEludm9rZU9yUmV0dXJuID0gew0KICAgICAgICBwYXJhbSgkQ21kKQ0KICAgICAgICBpZiAoJENtZCAtaXMgW1NjcmlwdEJsb2NrXSkgeyYgJENtZH0gZWxzZSB7JENtZH0NCiAgICB9DQogICAgaWYgKCRkZWNpZGVyKSB7JiAkSW52b2tlT3JSZXR1cm4gJGlmdHJ1ZX0gZWxzZSB7JiAkSW52b2tlT3JSZXR1cm4gJGlmZmFsc2V9DQp9CgpmdW5jdGlvbiBXcml0ZS1BUEwgew0KICAgIFtDbWRsZXRCaW5kaW5nKCldDQogICAgcGFyYW0oDQogICAgICAgIFtQYXJhbWV0ZXIoVmFsdWVGcm9tUGlwZWxpbmU9JHRydWUsIE1hbmRhdG9yeT0kVHJ1ZSldJFRleHQsDQogICAgICAgIFtBbGlhcygnTlMnKV1bU3dpdGNoXSROb1NpZ24sDQogICAgICAgIFtBbGlhcygnTk5MJywnTkwnKV1bU3dpdGNoXSROb05ld0xpbmUsDQogICAgICAgIFtTd2l0Y2hdJFBhc3NUaHJ1DQogICAgKQ0KICAgIGJlZ2luIHsNCiAgICAgICAgJFNpZ25SZ3ggPSAiW1wrXC1cIVwqXCNcQF9dIjsgJFRUID0gQCgpDQogICAgICAgICRJc1ZlcmJvc2UgPSAkUFNDbWRsZXQuTXlJbnZvY2F0aW9uLkJvdW5kUGFyYW1ldGVycy5WZXJib3NlDQogICAgfQ0KICAgIHByb2Nlc3Mge0ZsYXR0ZW4gJFRleHQgfCAlIHsNCiAgICAgICAgJExpbmUgPSAkXyAtc3BsaXQgImBuIg0KICAgICAgICAkTGluZVN5bWJvbCA9ICQoaWYgKCRsaW5lWzBdIC1tYXRjaCAiXm4/eD9uPyhcPiopKCRTaWduUmd4KS4qJCIpIHskTWF0Y2hlc1syXX0gZWxzZSB7IiJ9KQ0KICAgICAgICBpZiAoJElzVmVyYm9zZSkge1dyaXRlLVZlcmJvc2UgIiQoY29sIGkpTGluZVN5bWJvbDogJExpbmVTeW1ib2wgfCBMaW5lOiAkTGluZSQoY29sIHJTKSJ9DQogICAgICAgIDEuLiRMaW5lLkxlbmd0aCB8ICUgew0KICAgICAgICAgICAgJGlkeCA9ICRfIC0gMQ0KICAgICAgICAgICAgaWYgKCRpZHgpIHskVFQgKz0gImBuIiskTGluZVN5bWJvbCskTGluZVskaWR4XX0NCiAgICAgICAgICAgIGVsc2UgeyRUVCArPSAkTGluZVskaWR4XX0NCiAgICAgICAgfQ0KICAgIH19DQogICAgZW5kIHsNCiAgICAgICAgaWYgKCRJc1ZlcmJvc2UpIHtXcml0ZS1WZXJib3NlICIkKGNvbCBpKSQoUHJpbnQtTGlzdCAkVFQpJChjb2wgclMpIn0NCiAgICAgICAgZm9yICgkaT0wOyRpIC1sdCAkVFQuY291bnQ7JGkrKykgew0KICAgICAgICAgICAgW3N0cmluZ10kQ2h1bmsgPSAkVFRbJGldDQogICAgICAgICAgICBpZiAoJENodW5rWzBdIC1lcSAiYG4iKSB7JENodW5rID0gJENodW5rLlN1YnN0cmluZygxKTtXcml0ZS1Ib3N0fSAjIFNwZWNpYWwgY2FzZSBmb3IgbmV3IGxpbmUgdmlhIGBuDQogICAgICAgICAgICAkQ2h1bmsgPSAkQ2h1bmsgLXJlcGxhY2UgIl5uP3g/bj8oXD4qJFNpZ25SZ3gpIiwnJDEnDQogICAgICAgICAgICBpZiAoJENodW5rIC1ub3RtYXRjaCAiXlw+KiRTaWduUmd4LioiKSB7JENodW5rID0gIl8kQ2h1bmsifSAjIFVzZSBkZWZhdWx0IGFzIHdoaXRlDQogICAgICAgICAgICAkUHJlZml4Q29kZSA9ID86ICgkaSAtZXEgMCkgeyJ4JCg/OiAkTm9TaWduIHsnbid9IHsnJ30pIn0gez86ICgkaSAtbmUgKCRUVC5Db3VudCAtIDEpKSB7Im54In0gIm4kKD86ICROb05ld0xpbmUgeyd4J30geycnfSkifQ0KICAgICAgICAgICAgaWYgKCRUVC5Db3VudCAtZXEgMSkgeyRQcmVmaXhDb2RlID0gIiQoPzogJE5vU2lnbiB7J24nfSB7Jyd9KSQoPzogJE5vTmV3TGluZSB7J3gnfSB7Jyd9KSJ9DQogICAgICAgICAgICBpZiAoJElzVmVyYm9zZSkge1dyaXRlLVZlcmJvc2UgIiQoY29sIGkpUHJlZml4Q29kZTogJFByZWZpeENvZGUgfCBDaHVuazogJENodW5rJChjb2wgclMpIn0NCiAgICAgICAgICAgIFdyaXRlLUFQICIkUHJlZml4Q29kZSRDaHVuayIgLVBhc3NUaHJ1OiRQYXNzVGhydQ0KICAgICAgICB9DQogICAgfQ0KfQoKZnVuY3Rpb24gSlMtT1Ige2ZvcmVhY2ggKCRhIGluICRhcmdzKSB7JHIgPSBJbnZva2UtT3JSZXR1cm4gJGE7aWYgKCEkcil7Y29udGludWV9O3JldHVybiAkcn07cmV0dXJuICRyfQoKZnVuY3Rpb24gR2V0LVBhdGhWYXJTZXAge3BhcmFtKFtzdHJpbmddJE92ZXJyaWRlID0gIiIpDQoNCiAgICAkSXNVbml4ID0gJFBTVmVyc2lvblRhYmxlLlBsYXRmb3JtIC1lcSAiVW5peCINCiAgICByZXR1cm4gSlMtT1IgJE92ZXJyaWRlICg/OiAkSXNVbml4ICI6IiAiOyIpDQp9CgpmdW5jdGlvbiBBUC1SZXF1aXJlIHtwYXJhbShbUGFyYW1ldGVyKE1hbmRhdG9yeT0kVHJ1ZSldW0FsaWFzKCJGdW5jdGlvbmFsaXR5IiwiTGlicmFyeSIpXVtBcmd1bWVudENvbXBsZXRlcih7DQogICAgW091dHB1dFR5cGUoW1N5c3RlbS5NYW5hZ2VtZW50LkF1dG9tYXRpb24uQ29tcGxldGlvblJlc3VsdF0pXQ0KICAgIHBhcmFtKA0KICAgICAgICBbc3RyaW5nXSAkQ29tbWFuZE5hbWUsDQogICAgICAgIFtzdHJpbmddICRQYXJhbWV0ZXJOYW1lLA0KICAgICAgICBbc3RyaW5nXSAkV29yZFRvQ29tcGxldGUsDQogICAgICAgIFtTeXN0ZW0uTWFuYWdlbWVudC5BdXRvbWF0aW9uLkxhbmd1YWdlLkNvbW1hbmRBc3RdICRDb21tYW5kQXN0LA0KICAgICAgICBbU3lzdGVtLkNvbGxlY3Rpb25zLklEaWN0aW9uYXJ5XSAkRmFrZUJvdW5kUGFyYW1ldGVycw0KICAgICkNCiAgICAkQ29tcGxldGlvblJlc3VsdHMgPSBbU3lzdGVtLkNvbGxlY3Rpb25zLkdlbmVyaWMuTGlzdFtTeXN0ZW0uTWFuYWdlbWVudC5BdXRvbWF0aW9uLkNvbXBsZXRpb25SZXN1bHRdXTo6bmV3KCkNCiAgICAkTGliID0gQCgiSW50ZXJuZXQiLCJvczp3aW5kb3dzIiwib3M6bWFjIiwib3M6bGludXgiLCJvczp1bml4IiwiYWRtaW5pc3RyYXRvciIsInJvb3QiLCJkZXA6IiwibGliOiIsImxpYl90ZXN0OiIsIm1vZHVsZToiLCJtb2R1bGVfdGVzdDoiLCJmdW5jdGlvbjoiLCJzdHJpY3RfZnVuY3Rpb246IiwiYWJpbGl0eTplc2NhcGVfY29kZXMiLCJhYmlsaXR5OmVtb2ppcyIsImFiaWxpdHk6bmVyZF9mb250IiwiYWJpbGl0eTpsb25nX3BhdGhzIiwiYWJpbGl0eTpjb25zb2xlX21hbmlwdWxhdGlvbiIpDQogICAgJGpzT3IgPSB7Zm9yZWFjaCAoJGEgaW4gJGFyZ3MpIHskYSA9ICQoaWYoJGEgLWlzIFtzY3JpcHRibG9ja10peyYkYX1lbHNleyRhfSk7aWYgKCEkYSl7Y29udGludWV9O3JldHVybiAkYX07cmV0dXJuICRhfSAjIE1hbnVhbGx5IGVtYmVkZGVkIEpTLU9SDQogICAgJiAkanNPciB7JExpYiB8ID8geyRfIC1saWtlICIkV29yZFRvQ29tcGxldGUqIn19IHskTGliIHwgPyB7JF8gLWxpa2UgIiokV29yZFRvQ29tcGxldGUqIn19IHwgJSB7DQogICAgICAgICRDb21wbGV0aW9uUmVzdWx0cy5BZGQoW1N5c3RlbS5NYW5hZ2VtZW50LkF1dG9tYXRpb24uQ29tcGxldGlvblJlc3VsdF06Om5ldygkXywgJF8sICdQYXJhbWV0ZXJWYWx1ZScsICRfKSkNCiAgICB9DQogICAgcmV0dXJuICRDb21wbGV0aW9uUmVzdWx0cw0KfSldW1N0cmluZ10kTGliLCBbU2NyaXB0QmxvY2tdJE9uRmFpbCwgW1N3aXRjaF0kUGFzc1RocnUpDQoNCiAgICAkTG9hZE1vZHVsZSA9IHsNCiAgICAgICAgcGFyYW0oJEZpbGUsW2Jvb2xdJEltcG9ydCkNCiAgICAgICAgdHJ5IHtJbXBvcnQtTW9kdWxlICRGaWxlIC1lYSBzdG9wO3JldHVybiAxfSBjYXRjaCB7fQ0KICAgICAgICAkTGliPUFQLUNvbnZlcnRQYXRoICI8TElCPiI7JExGID0gIiRMaWJcJEZpbGUiDQogICAgICAgICRmID0gJExGLCIkTEYucHNtMSIsIiRMRi5kbGwiIHwgPyB7dGVzdC1wYXRoIC10IGxlYWYgJF99IHwgc2VsZWN0IC1mIDENCiAgICAgICAgaWYgKCRmIC1hbmQgJEltcG9ydCkgew0KICAgICAgICAgICAgSW1wb3J0LU1vZHVsZSAkZg0KICAgICAgICAgICAgaWYgKCQ/KSB7cmV0dXJuICRmfSBlbHNlIHtXcml0ZS1BUCAiIUZhaWxlZCB0byBpbXBvcnQgWyRGaWxlIC0+ICRGXSI7cmV0dXJuIDB9DQogICAgICAgIH0NCiAgICAgICAgcmV0dXJuICRmDQogICAgfQ0KICAgICRJbnZva2VPclJldHVybiA9IHtwYXJhbSgkQ21kLCAkZmFsbGJhY2s9MCkgaWYgKCRDbWQgLWlzIFtTY3JpcHRCbG9ja10pIHt0cnl7JiAkQ21kfWNhdGNoeyRmYWxsYmFja319IGVsc2UgeyRDbWR9fQ0KICAgIGlmICghJE9uRmFpbCkgeyRQYXNzVGhydSA9ICR0cnVlfQ0KICAgICRTdGF0ID0gJChzd2l0Y2ggLXJlZ2V4ICgkTGliLnRyaW0oKSkgew0KICAgICAgICAiXkludGVybmV0JCIgICAgICAgICAgICAgICAgICAgICAgIHt0ZXN0LWNvbm5lY3Rpb24gZ29vZ2xlLmNvbSAtQ291bnQgMSAtUXVpZXR9DQogICAgICAgICJeYWRtaW4oaXN0cmF0b3IpPyR8XnJvb3QkIiAgICAgICAge1Rlc3QtQWRtaW5pc3RyYXRvcn0NCiAgICAgICAgIl5kZXA6KC4qKSQiICAgICAgICAgICAgICAgICAgICAgICB7R2V0LVdoZXJlICRNYXRjaGVzWzFdfQ0KICAgICAgICAiXihsaWJ8bW9kdWxlKTooLiopJCIgICAgICAgICAgICAgIHskTG9hZE1vZHVsZS5pbnZva2UoJE1hdGNoZXNbMl0sICR0cnVlKX0NCiAgICAgICAgIl4obGlifG1vZHVsZSlfdGVzdDooLiopJCIgICAgICAgICB7JExvYWRNb2R1bGUuaW52b2tlKCRNYXRjaGVzWzJdKX0NCiAgICAgICAgIl5mdW5jdGlvbjooLiopJCIgICAgICAgICAgICAgICAgICB7Z2NtICRNYXRjaGVzWzFdIC1lYSBTaWxlbnRseUNvbnRpbnVlfQ0KICAgICAgICAiXnN0cmljdF9mdW5jdGlvbjooLiopJCIgICAgICAgICAgIHtUZXN0LVBhdGggIkZ1bmN0aW9uOlwkKCRNYXRjaGVzWzFdKSJ9DQogICAgICAgICJeb3M6KHdpbihkb3dzKT98bGludXh8bWFjfHVuaXgpJCIgeyRvID0gR2V0LU9TOyRJc1VuaXggPSAkUFNWZXJzaW9uVGFibGUuUGxhdGZvcm0gLWVxICJVbml4Ijtzd2l0Y2ggLXJlZ2V4ICgkTWF0Y2hlc1sxXSkgew0KICAgICAgICAgICAgIl53aW4iICAge3JldHVybiAkbyAtZXEgIldpbmRvd3MifQ0KICAgICAgICAgICAgImxpbnV4IiAge3JldHVybiAkbyAtZXEgIkxpbnV4In0NCiAgICAgICAgICAgICJtYWMiICAgIHtyZXR1cm4gJG8gLWVxICJNYWNPUyJ9DQogICAgICAgICAgICAidW5peCIgICB7cmV0dXJuICRJc1VuaXh9DQogICAgICAgIH19DQogICAgICAgICJeYWJpbGl0eTooLispJCIgICAgIHskbSA9ICRNYXRjaGVzWzFdO0pTLU5DUSAoJiAkSW52b2tlT3JSZXR1cm4gKEB7DQogICAgICAgICAgICBlc2NhcGVfY29kZXMgPSAkSG9zdC5VSS5TdXBwb3J0c1ZpcnR1YWxUZXJtaW5hbA0KICAgICAgICAgICAgZW1vamlzID0gJGVudjpXVF9TRVNTSU9OIC1vciAkZW52OldUX1BST0ZJTEVfSUQgLW9yICgkZW52OlRFUk1fUFJPR1JBTSAtbWF0Y2ggJ3ZzY29kZXxpVGVybS5hcHB8QXBwbGVfVGVybWluYWwnKQ0KICAgICAgICAgICAgbmVyZF9mb250ID0geyRwPSRIb3N0LlVJLlJhd1VJLkN1cnNvclBvc2l0aW9uO1dyaXRlLUhvc3QgLU5vTmV3bGluZSAoW2NoYXJdOjpDb252ZXJ0RnJvbVV0ZjMyKDB4RjA1MzEpKTskbj0kSG9zdC5VSS5SYXdVSS5DdXJzb3JQb3NpdGlvbjskSG9zdC5VSS5SYXdVSS5DdXJzb3JQb3NpdGlvbj0kcDtXcml0ZS1Ib3N0IC1Ob05ld2xpbmUgJyAgJzskSG9zdC5VSS5SYXdVSS5DdXJzb3JQb3NpdGlvbj0kcDsoJG4uWC0kcC5YKS1lcSAxfQ0KICAgICAgICAgICAgbG9uZ19wYXRocyA9ICRQU1ZlcnNpb25UYWJsZS5QbGF0Zm9ybSAtZXEgIlVuaXgiIC1vciAoR2V0LUl0ZW1Qcm9wZXJ0eSAtUGF0aCAiSEtMTTpcU1lTVEVNXEN1cnJlbnRDb250cm9sU2V0XENvbnRyb2xcRmlsZVN5c3RlbSIgfCAlIGxvbmdwYXRoc2VuYWJsZWQpDQogICAgICAgICAgICBjb25zb2xlX21hbmlwdWxhdGlvbiA9ICFbU3lzdGVtLkNvbnNvbGVdOjpJc091dHB1dFJlZGlyZWN0ZWQgLWFuZCAoJEhvc3QuTmFtZSAtZXEgJ0NvbnNvbGVIb3N0JykNCiAgICAgICAgfVskbV0pKSB7V3JpdGUtQVAgIiFSZXF1aXJlZCBhYmlsaXR5IFskbV0gaXMgbm90IHN1cHBvcnRlZCBvbiB0aGlzIHBsYXRmb3JtLiI7IHRocm93ICdCQURfU0VMRUNUT1InfX0NCiAgICAgICAgZGVmYXVsdCB7V3JpdGUtQVAgIiFJbnZhbGlkIHNlbGVjdG9yIHByb3ZpZGVkIFskKCIkTGliIi5zcGxpdCgnOicpWzBdKV0iO3Rocm93ICdCQURfU0VMRUNUT1InfQ0KICAgIH0pDQogICAgaWYgKCEkU3RhdCAtYW5kICRPbkZhaWwpIHsmICRPbkZhaWx9DQogICAgaWYgKCRQYXNzVGhydSAtb3IgISRPbkZhaWwpIHtyZXR1cm4gJFN0YXR9DQp9CgpmdW5jdGlvbiBQcmludC1MaXN0IHtwYXJhbSgkeCwgW1N3aXRjaF0kSW5SZWN1cnNlKQ0KDQogICAgaWYgKCR4LmNvdW50IC1sZSAxKSB7cmV0dXJuID86KCRJblJlY3Vyc2UpeyR4fXsiWyR4XSJ9fSBlbHNlIHsNCiAgICAgICAgcmV0dXJuICJbJCgoJHggfCAlIHtQcmludC1MaXN0ICRfIC1JblJlY3Vyc2V9KSAtam9pbiAnLCAnKV0iDQogICAgfQ0KfQoKZnVuY3Rpb24gUHJvY2Vzcy1Vbmljb2RlIHsNCiAgICAkRmluYWxBcmdzID0gRmxhdHRlbiAkYXJncw0KICAgICMgUG93ZXJTaGVsbCBDb3JlIHN5bnRheCB3aGVuIHByb2Nlc3NlZCBieSBQb3dlclNoZWxsIE5hdGl2ZQ0KICAgIGlmICgiJEZpbmFsQXJncyIgLW1hdGNoICJ1eyhcdyspfSIpIHsNCiAgICAgICAgcmV0dXJuIFtSZWdleF06OlVuZXNjYXBlKCgiJEZpbmFsQXJncyIgLXJlcGxhY2UgInV7KFx3Kyl9IiwnXHUkMScpKQ0KICAgIH0NCiAgICBpZiAoISgkRmluYWxBcmdzIHwgPyB7JF8gLWlzbm90IFtpbnRdfSkpIHsNCiAgICAgICAgcmV0dXJuIFtjaGFyW11dJEZpbmFsQXJncyAtam9pbiAnJw0KICAgIH0NCiAgICByZXR1cm4gJGFyZ3MNCn0KCmZ1bmN0aW9uIENvbnZlcnQtVG9CYXNlNjQge3BhcmFtKFtQYXJhbWV0ZXIoVmFsdWVGcm9tUGlwZWxpbmU9JHRydWUpXVtTdHJpbmddJFRleHQsIFtWYWxpZGF0ZVNldCgiVVRGOCIsIlVuaWNvZGUiKV1bU3RyaW5nXSRFbmNvZGluZyA9ICJVVEY4IikNCg0KICAgIFtTeXN0ZW0uQ29udmVydF06OlRvQmFzZTY0U3RyaW5nKFtTeXN0ZW0uVGV4dC5FbmNvZGluZ106OiRFbmNvZGluZy5HZXRCeXRlcygkVGV4dCkpDQp9CgpmdW5jdGlvbiBHZXQtT1Mgew0KICAgIGlmICgkUFNWZXJzaW9uVGFibGUuUFNFZGl0aW9uIC1lcSAnQ29yZScpIHsNCiAgICAgICAgaWYgKCRJc1dpbmRvd3MpIHtyZXR1cm4gJ1dpbmRvd3MnfQ0KICAgICAgICBlbHNlaWYgKCRJc0xpbnV4KSB7cmV0dXJuICdMaW51eCd9DQogICAgICAgIGVsc2VpZiAoJElzTWFjT1MpIHtyZXR1cm4gJ01hY09TJ30NCiAgICB9IGVsc2Uge3JldHVybiAnV2luZG93cyd9DQp9CgpmdW5jdGlvbiBBUC1Db252ZXJ0UGF0aCB7cGFyYW0oW1BhcmFtZXRlcihNYW5kYXRvcnk9JFRydWUpXVtTdHJpbmddJFBhdGgpDQoNCiAgICAkUGF0aFNlcCA9IFtJTy5QYXRoXTo6RGlyZWN0b3J5U2VwYXJhdG9yQ2hhcg0KICAgIHJldHVybiAkUGF0aCAtcmVwbGFjZQ0KICAgICAgICAiPERlcD4iLCI8TGliPiR7UGF0aFNlcH1EZXBlbmRlbmNpZXMiIC1yZXBsYWNlDQogICAgICAgICI8TGliPiIsIjxIb21lPiR7UGF0aFNlcH1BUC1MaWJyYXJpZXMiIC1yZXBsYWNlDQogICAgICAgICI8Q29tcChvbmVudHMpPz4iLCI8SG9tZT4ke1BhdGhTZXB9QVAtQ29tcG9uZW50cyIgLXJlcGxhY2UNCiAgICAgICAgIjxIb21lPiIsJFBTSGVsbH0KCmZ1bmN0aW9uIEZsYXR0ZW4ge3BhcmFtKFtvYmplY3RbXV0keCkNCg0KICAgIGlmICghKCRYIC1pcyBbYXJyYXldKSkge3JldHVybiAkeH0NCiAgICBpZiAoJFguY291bnQgLWVxIDEpIHsNCiAgICAgICAgcmV0dXJuICR4IHwgJSB7JF99DQogICAgfQ0KICAgICR4IHwgJSB7RmxhdHRlbiAkX30NCn0KCmZ1bmN0aW9uIEdldC1Fc2NhcGUgew0KICAgIGlmICgkbnVsbCAtZXEgJEFQX0NPTlNPTEUuY3VzdG9tRmxhZ3MuX19kZXRlY3RlZF9lc2NhcGVfY29kZXMpIHskQVBfQ09OU09MRS5jdXN0b21GbGFncy5fX2RldGVjdGVkX2VzY2FwZV9jb2RlcyA9IEFQLVJlcXVpcmUgImFiaWxpdHk6ZXNjYXBlX2NvZGVzIn0NCiAgICBpZiAoISRBUF9DT05TT0xFLmN1c3RvbUZsYWdzLl9fZGV0ZWN0ZWRfZXNjYXBlX2NvZGVzIC1hbmQgISRBUF9DT05TT0xFLmN1c3RvbUZsYWdzLmZvcmNlVW5peEVzY2FwZXMpIHt0aHJvdyAiW0FQQ29uc29sZTo6R2V0LUVzY2FwZV0gWW91ciBjb25zb2xlIGRvZXMgbm90IHN1cHBvcnQgQU5TSSBlc2NhcGUgY29kZXMuIFlvdSBjYW4gc2V0IGAkQVBfQ09OU09MRS5jdXN0b21GbGFncy5ub1VuaXhFc2NhcGVzID0gYCR0cnVlIHRvIGRpc2FibGUgdW5peCBlc2NhcGUgY29kZXMuIE9yLCB1c2U6IGAkQVBfQ09OU09MRS5jdXN0b21GbGFncy5mb3JjZVVuaXhFc2NhcGVzIHRvIGF0dGVtcHQgaXQgYW55d2F5cyJ9DQogICAgIyBXZSBkbyB0aGlzLCBiZWNhdXNlIFBvd2VyU2hlbGwgTmF0aXZlIGRvZXNuJ3Qga25vdyBgZQ0KICAgIHJldHVybiBbQ2hhcl0weDFiICMgYGUNCn0KCmZ1bmN0aW9uIEdldC1Db2xvciB7DQogICAgPCMgIC5EZXNjcmlwdGlvbg0KICAgICAgICBGZXRjaGVzIGJhc2ljIGNvbG9ycyB1c2luZyB0aGUgVW5pY29kZSBFc2NhcGUgc2VxdWVuY2VzDQogICAgIz4NCiAgICBwYXJhbSAoDQogICAgICAgIFtWYWxpZGF0ZVNldCgNCiAgICAgICAgICAgICdyJywncmVzZXQnLCdyUycsJ3Jlc2V0U3R5bGVzJywnZCcsJ2RpbScsJ3MnLCdzdHJpa2UnLCd1JywndW5kZXJsaW5lJywnYicsJ2JvbGQnLCdpJywnaXRhbGljJywnYmwnLCdibGluaycsJ3JldmVyc2UnLCdoJywnaGlkZGVuJywNCiAgICAgICAgICAgICdCbGFjaycsJ0RhcmtCbHVlJywnRGFya0dyZWVuJywnRGFya0N5YW4nLCdEYXJrUmVkJywnRGFya01hZ2VudGEnLCdEYXJrWWVsbG93JywnR3JheScsJ0RhcmtHcmF5JywnQmx1ZScsJ0dyZWVuJywnQ3lhbicsJ1JlZCcsJ01hZ2VudGEnLCdZZWxsb3cnLCdXaGl0ZScsDQogICAgICAgICAgICAnYmcuQmxhY2snLCdiZy5EYXJrQmx1ZScsJ2JnLkRhcmtHcmVlbicsJ2JnLkRhcmtDeWFuJywnYmcuRGFya1JlZCcsJ2JnLkRhcmtNYWdlbnRhJywnYmcuRGFya1llbGxvdycsJ2JnLkdyYXknLCdiZy5EYXJrR3JheScsJ2JnLkJsdWUnLCdiZy5HcmVlbicsJ2JnLkN5YW4nLCdiZy5SZWQnLCdiZy5NYWdlbnRhJywnYmcuWWVsbG93JywnYmcuV2hpdGUnDQogICAgICAgICldW1N0cmluZ1tdXSRDb2RlLA0KICAgICAgICBbQWxpYXMoJ2JnJyldW1N3aXRjaF0kQmFja2dyb3VuZCwNCiAgICAgICAgW1N3aXRjaF0kQ29kZVN0cmluZw0KICAgICkNCiAgICBpZiAoJEFQX0NPTlNPTEUuY3VzdG9tRmxhZ3Mubm9Vbml4RXNjYXBlcykge3JldHVybn0NCiAgICAkQWxpYXNUYWJsZSA9IEB7dSA9ICd1bmRlcmxpbmUnO2IgPSAnYm9sZCc7aSA9ICdpdGFsaWMnO3IgPSAncmVzZXQnO3JTID0gJ3Jlc2V0U3R5bGVzJztzID0gJ3N0cmlrZSc7ZCA9ICdkaW0nO2JsID0gJ2JsaW5rJztoID0gJ2hpZGRlbid9DQogICAgaWYgKCEkR2xvYmFsOkFQX0NPTE9SX1RBQkxFKSB7DQogICAgICAgICRUQkwgPSAkR2xvYmFsOkFQX0NPTE9SX1RBQkxFID0gQHtyZXNldCA9IDA7Ym9sZCA9IDE7ZGltID0gMjtpdGFsaWMgPSAzO3VuZGVybGluZSA9IDQ7YmxpbmsgPSA1O3JldmVyc2UgPSA3O2hpZGRlbiA9IDg7c3RyaWtlID0gOTtyZXNldFN0eWxlcyA9ICcyMjsyMzsyNDsyNTsyNzsyODsyOSd9DQogICAgICAgIDAsMSB8ICUgew0KICAgICAgICAgICAgJEJnSW5kZXggPSAkXw0KICAgICAgICAgICAgMCwxIHwgJSB7DQogICAgICAgICAgICAgICAgJFNwY0luZGV4ID0gJF8NCiAgICAgICAgICAgICAgICAkaSA9IDANCiAgICAgICAgICAgICAgICAnQmxhY2suVHxSZWR8R3JlZW58WWVsbG93fEJsdWV8TWFnZW50YXxDeWFufFdoaXRlJy5zcGxpdCgnfCcpIHwgJSB7DQogICAgICAgICAgICAgICAgICAgICRJbmNyID0gJEJnSW5kZXggKiAxMA0KICAgICAgICAgICAgICAgICAgICAkQ29sTmFtZSA9ICgoJycsJ2JnLicpWyRCZ0luZGV4XSkrKCgnRGFyaycsJycpWyRTcGNJbmRleF0pKyRfDQogICAgICAgICAgICAgICAgICAgICRDb2xTcGFjZSA9ICgzMCwgOTApWyRTcGNJbmRleF0gKyAkSW5jcg0KICAgICAgICAgICAgICAgICAgICAkVEJMLiRDb2xOYW1lID0gJENvbFNwYWNlKygkaSsrKQ0KICAgICAgICAgICAgICAgIH0NCiAgICAgICAgICAgIH0NCiAgICAgICAgfQ0KICAgICAgICBAe0RhcmtHcmF5ID0gJ0JsYWNrLlQnO0JsYWNrID0gJ0RhcmtCbGFjay5UJztHcmF5ID0gJ0RhcmtXaGl0ZSd9LkdldEVudW1lcmF0b3IoKSB8ICUgew0KICAgICAgICAgICAgJFRCTC4oJF8uS2V5KSA9ICRUQkwuKCRfLlZhbHVlKQ0KICAgICAgICAgICAgJFRCTC4oJ2JnLicrJF8uS2V5KSA9ICRUQkwuKCdiZy4nKyRfLlZhbHVlKQ0KICAgICAgICAgICAgJFRCTC5yZW1vdmUoJF8uVmFsdWUpDQogICAgICAgICAgICAkVEJMLnJlbW92ZSgnYmcuJyskXy5WYWx1ZSkNCiAgICAgICAgfQ0KICAgIH0NCiAgICAkQ29kZXMgPSAoJENvZGUrJEFyZ3MgfCAlIHsNCiAgICAgICAgJEdsb2JhbDpBUF9DT0xPUl9UQUJMRS4oSlMtT1IgJEFsaWFzVGFibGUuJF8gJF8pDQogICAgfSkgLWpvaW4gJzsnDQogICAgaWYgKCRDb2RlU3RyaW5nKSB7cmV0dXJuICRDb2Rlc30NCiAgICByZXR1cm4gKEdldC1Fc2NhcGUpICsgJ1snICsgJENvZGVzICsgJ20nICMgVXNpbmcgc3RyaW5nIGNvbmNhdCBmb3IgZmFzdGVyIHByb2Nlc3NpbmcNCn0KClNldC1BbGlhcyA/OiBJbnZva2UtVGVybmFyeQpTZXQtQWxpYXMgY29sIEdldC1Db2xvcgpTZXQtQWxpYXMgd2hpY2ggR2V0LVdoZXJl")
} elseif($AP_CONSOLE.warnOnCompileRun) {& $AP_CONSOLE.warnOnCompileRun}
# ========================================END=OF=COMPILER=================================================================|
$Dbg = $Dbg -or $PSBoundParameters.ContainsKey('Verbose') -or $PSBoundParameters.ContainsKey('Debug')
$Ver = "1.6 (APC: $($AP_CONSOLE.version))"

# Track all AP-Console Commands
if (!$AP_CONSOLE -or !$AP_CONSOLE.functions) {
    Write-APL "!","AP-Console not loaded, only a valid AP-Console session can run this command. Alternatively, define all the functions you'd like to support in ","+`$AP_CONSOLE.functions"
    exit 1
}
if (!$AP_CONSOLE.Version -or $AP_CONSOLE.Version -lt 1.2) {
    Write-APL "!","AP-Console Version is too old, please update to at least 1.2 to use this command"
    exit 1
}
function Get-AllNestedFunctionalDeps ([System.Management.Automation.Language.Ast]$RootAst, [System.Management.Automation.Language.Token[]]$Tokens, $Depth = 0, $SeenFuncs = @{}) {
    if (!$RootAst) {return}
    $ClassRefs = $RootAst.findAll({$args[0] -is [System.Management.Automation.Language.TypeDefinitionAst]}, $true) | Group-Object name | % Group | select -f 1 | ? {
        $AP_CONSOLE.classes.Contains($_.Name) -and !$SeenClassDefs.$_.Name
    } | % {
        $SeenClassDefs.($_.Name) = $_.Extent.Text # Store the class definition
    }
    ScanFor-ForcedCommands -Tokens $Tokens
    $DefinedFuncs = $RootAst.findAll({$args[0] -is [System.Management.Automation.Language.FunctionDefinitionAst]}, $true) | % name | select -Unique
    $Commands = $RootAst.findAll({$args[0] -is [System.Management.Automation.Language.CommandAst]}, $true) | % {$_.CommandElements[0]} | % value | select -Unique | % {
        # Ignore if it's not a known AP-Function / Alias or is one of the defined functions in the file
        if ((!$TmpHash.$_ -and $_ -notin $Aliases) -or $SeenFuncs.$_ -or ($_ -in $DefinedFuncs)) {return}
        $SeenFuncs.$_++
        $Name = $_
        $Cmd = Get-Command $_ -ea SilentlyContinue
        if ($Cmd.ResolvedCommandName) {
            [PSCustomObject]@{
                Name = $_
                Depth = $Depth
                Type = "Alias"
            }
            $SeenFuncs.$Name++
            $Name = $Cmd.ResolvedCommandName
            $Cmd = Get-Command $Name -ea SilentlyContinue
        }
        $Ast = $Cmd.ScriptBlock.Ast
        $SubTokens = @()
        if (!$Ast) {return}
        [void][System.Management.Automation.Language.Parser]::ParseInput($Cmd.ScriptBlock.ToString(), [ref]$SubTokens, [ref]$null)
        return @([PSCustomObject]@{
            Name = $Name
            Depth = $Depth
            Type = "Function"
        })+(Get-AllNestedFunctionalDeps $Ast $SubTokens -Depth ($Depth + 1) -SeenFuncs $SeenFuncs)
    }

    return Flatten $Commands | ? {$_} | Sort-Object # To make sure the base64 code is deterministic
}

function Write-CompiledFile ($Data) {
    if ($OverwriteSrc) {$OutputFolder = Split-Path $File}
    if ((Split-Path $File) -eq $OutputFolder -and !$OverwriteSrc) {
        $Outfile = "$((Split-Path -leaf $File).replace('.ps1','-Compiled.ps1'))"
    } else {
        $Outfile = "$(Split-Path -leaf $File)"
    }
    $enc = JS-OR {
        $e = Get-FileEncoding $File
        if ($e -in "utf32","unicode","bigendianunicode") {""} else {[System.Text.Encoding]::$e}
    } "unicode"
    $Verb = ?: $Strip "Unc" "C"
    Write-APL ">+","${Verb}ompiled [","+$OutFile","] with Encoding [","+$(JS-OR $Enc.EncodingName $Enc)","] in Folder [","*$OutputFolder","]"
    $Data | Out-File -Encoding $Enc "$OutputFolder\$OutFile"
}

function Remove-OldInjecter ($Data) {
    $ReplaceExpr = "(?s)\# ?=+START=OF=COMPILER=+\|`n.+\# ?=+END=OF=COMPILER=+\|"
    return $Data -replace "$ReplaceExpr`n|`n$ReplaceExpr",""
}
function ScanFor-ForcedCommands {
    param([System.Management.Automation.Language.Token[]]$Tokens)
    # Scan for forced required functions
    # Example: ap-compiler: Write-APL,AP-Require
    $tokens | ? kind -eq 'comment' | ? text -Match "^\s*..?\s*ap-compiler?\:" | % {$_ -replace "^\s*..?\s*ap-compiler?\: *(.+?) *(?<a>\#\>)?$",'$1' -split ","} | % {$_.Trim()} | ? {$_} | % {
        Write-APL ">#","@AP-Compiler Forced Command: ","+$_"
        if ($_ -notin $TmpHash.Keys -and $_ -notin $Aliases) {Throw "Invalid AP-Compiler Forced Command [$_]";exit 1}
        $script:ForcedDependencies += ,$_
    }
}

# Build a minimal "thin shim" for a specific scriptblock ? used to inject AP Console
# dependencies into argument-completer scriptblocks, which PowerShell evaluates in
# a fresh scope at tab-completion time and therefore can't see the script-scope
# functions defined by the main compiler block.
#
# Returns the shim text (comment + one-line base64 iex) or $null if the scriptblock
# doesn't call any AP Console functions and therefore needs nothing.
function Build-ThinShim {
    param([System.Management.Automation.Language.ScriptBlockAst]$SbAst)
    # Get-AllNestedFunctionalDeps mutates $script:ForcedDependencies and $Script:SeenClassDefs.
    # Snapshot and restore so a thin-shim scan doesn't pollute the main compiler block.
    $savedForced = $script:ForcedDependencies
    $savedSeenClasses = $Script:SeenClassDefs.Clone()
    $script:ForcedDependencies = @()
    try {
        $sbTokens = @()
        [void][System.Management.Automation.Language.Parser]::ParseInput($SbAst.ToString(), [ref]$sbTokens, [ref]$null)
        # Fresh $SeenFuncs so we capture THIS scriptblock's deps (the parent's call
        # already filled the global $SeenFuncs with the whole script's deps).
        $deps = @(Get-AllNestedFunctionalDeps $SbAst $sbTokens -SeenFuncs @{})
        if (!$deps) {return $null}

        $need2Import = @{}
        $need2ImportAL = @{}
        $deps | % {
            $name = $_.Name -replace '^\w+\:(\S+)$','$1'
            if ($_.Type -eq 'Function') {$need2Import.$name++}
            elseif ($name -ne 'Item') {
                $need2ImportAL.$name++
                $need2Import.((Get-Alias $name).Definition)++
            }
        }
        $finalSet = @($need2Import.Keys) | Sort-Object
        $finalAlSet = @($need2ImportAL.Keys) | Sort-Object -Unique
        $code = $finalSet | % {"function $_ {1}{0}{2}" -f (Get-Command $_ -CommandType Function -ea 0).ScriptBlock,'{',"}`n"}
        $code += $finalAlSet | % {"Set-Alias $_ {0}" -f ((Get-Alias $_).Definition)}
        if (!$code) {return $null}

        $b64 = Convert-ToBase64 ($code -join "`n")
        return "# AP Console compile thin shim`n& (Get-Alias iex) ([System.Text.Encoding]::UTF8.GetString([Convert]::FromBase64String(""$b64"")))`n"
    } finally {
        $script:ForcedDependencies = $savedForced
        $Script:SeenClassDefs = $savedSeenClasses
    }
}

# Regex that matches a previously-injected thin shim (comment + the iex line).
# Used both for stripping on re-compile and during -Strip (uncompile).
$Script:ThinShimPattern = "(?m)^[ \t]*# AP Console compile thin shim[^\n]*\n[ \t]*& \(Get-Alias iex\)[^\n]*\n"

$TmpHash = @{}
$AP_CONSOLE.functions | % {$TmpHash.$_ = $_}
$Aliases = Get-Alias | ? {$TmpHash.($_.Definition)} | % {"$_"}

# Validation
if (!$File -or !(Test-Path -type Leaf $File)) {Throw "Invalid File [$File]";exit}
if (!(Test-Path -type Container $OutputFolder)) {Throw "Invalid Folder [$OutputFolder]";exit}
if ($File -notmatch ".\.ps1$") {Throw "Invalid File Type [$File], expected *.ps1";exit}
$File = (Get-Item $File).FullName
$OutputFolder = (Get-Item $OutputFolder).FullName

if ($Strip) {
    Write-APL "*","Uncompiling File [","+$File","]"
    $OverwriteSrc = $true
    $OData = $Data = [IO.File]::ReadAllText($File)
    $Data = Remove-OldInjecter $Data
    # Also strip thin shims injected into argument-completer scriptblocks.
    $Data = $Data -replace $Script:ThinShimPattern, ""
    if ($OData -eq $Data) {
        Write-APL ">!","No Compiler Code Found, File is already uncompiled!"
        exit 0
    }
    Write-APL ">+","Uncompiled File!"
    $Data = $Data -replace "(?s)\# ?=+START=OF=COMPILER=+\|`n.+\# ?=+END=OF=COMPILER=+\|",""
    Write-CompiledFile $Data
    exit 0
}

# Let's process the file
$Data = [IO.File]::ReadAllLines($File)
$Script:Need2Import = @{}
$Script:Need2ImportAL = @{}
$Script:BlackListFunctions = @{"IN-Code-Debug-Console"=1;"Get-APIKey"=1;"Get-GMAIL"=1;"Backup"=1}
Write-APL "*","Compiling ","+$(Split-Path -leaf $File):"

# Use AST to detect the functions used in this script
$Tokens = @() # Where the comments will be scannable
$Script:ASTT = [System.Management.Automation.Language.Parser]::ParseFile($File, [ref]$Tokens, [ref]$null)
$Script:SeenClassDefs = @{}
$script:ForcedDependencies = @()
$Script:Functions = @(Get-AllNestedFunctionalDeps $Script:ASTT $Tokens)

$ForcedFakeExpr = "{$($script:ForcedDependencies -join ";")}"
$ForcedFakeAst = [System.Management.Automation.Language.Parser]::ParseInput($ForcedFakeExpr, [ref]$Tokens, [ref]$null)
$Script:Functions += Get-AllNestedFunctionalDeps $ForcedFakeAst $Tokens

if ($Dbg) {
    Write-APL ">*","Globally detected functions:"
    $MaxNameSize = [math]::Max(($Script:Functions | % {$_.Name.Length} | Measure-Object -Maximum).Maximum, ($SeenClassDefs.Keys | % Length | Measure-Object -Maximum).Maximum)+3
    $MaxNameSize = [math]::Clamp($MaxNameSize, 23, [Math]::Max(24, [Console]::WindowWidth * .5))
    $Script:Functions | % {
        Write-APL ">>#","+$($_.Name) ","#$("." * [Math]::max(0, $MaxNameSize - $_.Name.length)) ","@$($_.Type.PadLeft(8))","# | Depth: ","@$($_.Depth)"
    }
    $SeenClassDefs.Keys | % {
        Write-APL ">>#","+$($_) ","#$("." * [Math]::max(0, $MaxNameSize - $_.length)) ","@$("Class".PadLeft(8))","# | Depth: ","@0"
    }
}
$Script:Functions | % {
    $Name = $_.Name
    $Type = $_.Type
    # Strip single-colon scope qualifiers (global:, script:, local:) but
    # NOT `::` namespace separators (apc_ui::Foo, wt::Bar). Negative
    # lookahead `(?!\:)` ensures we don't match `wt::Foo` as `wt:` + `:Foo`.
    $Name = $Name -replace "^\w+\:(?!\:)(\S+)$",'$1'
    if ($Type -eq "Function") {$Script:Need2Import.$Name++} else {
        if ($Name -eq "Item") {return}
        $Script:Need2ImportAL.$Name++
        $Need2Import.((Get-Alias $Name).Definition)++
    }
}

$FinalSet = @($Need2Import.Keys) | ? {!$OtroFunc.$_}
$FinalAlSet = @($Need2ImportAL.Keys) | select -unique
$Code = $FinalSet | % {"function $_ {1}{0}{2}" -f $(if ($BlackListFunctions.$_) {"Write-Host -f yellow '[AP-COMPILER] Module [$_] disabled for this program'"} else {(Get-Command $_ -CommandType Function -ea 0).ScriptBlock}),"{","}`n"}
$Code += $FinalAlSet | % {"Set-Alias $_ {0}" -f ((Get-Alias $_).Definition)}
$Code += $SeenClassDefs.Values
if ($Code) {
    if ($FinalSet -and !$Dbg)            {Write-APL ">*","@Adding Functions $(Print-List $FinalSet)"}
    if ($FinalALSet -and !$Dbg)          {Write-APL ">*","@Adding Aliases   $(Print-List $FinalALSet)"}
    if ($SeenClassDefs.Count -and !$Dbg) {Write-APL ">*","@Adding Classes   $(Print-List $SeenClassDefs.Keys)"}
    $Injecter = @(
        ""
        "# =======================================START=OF=COMPILER================================================================|"
        "#    The Following Code was added by AP-Compiler $Ver To Make this program independent of AP-Core Engine"
        "#    GitHub: https://github.com/avdaredevil/AP-Compiler"
        "# ========================================================================================================================|"
        '$Script:PSHell=$(if($PSHell){$PSHell}elseif($PSScriptRoot){$PSScriptRoot}else{"."});'
        "if(`$AP_CONSOLE.mode -ne 'main' -or `$AP_CONSOLE.customFlags.runAsCompiled) {"
        "    `$Script:AP_CONSOLE = [PsCustomObject]@{version=[version]'$($AP_CONSOLE.Version)'; mode = 'shim'; customFlags = @{}}"
        "    function B64 {$("${Function:Convert-FromBase64}".trim() -replace "(`r?`n){2,}"," ")}"
        "    # This syntax is to prevent AV's from misclassifying this as anything but innocuous"
        "    & (Get-Alias iex) (B64 ""$(Convert-ToBase64 ($Code -join "`n"))"")"
        "} elseif(`$AP_CONSOLE.warnOnCompileRun) {& `$AP_CONSOLE.warnOnCompileRun}"
        "# ========================================END=OF=COMPILER=================================================================|"
    ) -join "`n"
}
$Data = $Data -join "`n"
$NewCode = Remove-OldInjecter $Data
if ($NewCode -ne $Data) {
    Write-APL ">!","Old Compiler Code Detected... Removing..."
    $Data = $NewCode
}

# Also strip any previously-injected thin shims so re-compile doesn't duplicate them.
$stripped = $Data -replace $Script:ThinShimPattern, ""
if ($stripped -ne $Data) {
    Write-APL ">!","Old Thin-Shim Code Detected... Removing..."
    $Data = $stripped
}

# --- Argument-completer thin-shim injection ---
# Argument-completer scriptblocks (both `Register-ArgumentCompleter -ScriptBlock {...}`
# and `[ArgumentCompleter({...})]` parameter attributes) run in a FRESH scope at
# tab-completion time. They don't see the script-scope functions the main compiler
# block defines, so a call to e.g. `Do-ArgMatch` inside a completer breaks in a
# compiled script. Fix: inject a minimal self-contained shim at the top of each
# completer scriptblock with just the deps that scriptblock actually uses.
#
# Parse $Data (not $File) so AST offsets align with the current string ? the main
# AST came from ParseFile and its offsets count \r\n as 2 chars, which won't match
# $Data's normalized \n-only line endings.
$astForPositions = [System.Management.Automation.Language.Parser]::ParseInput($Data, [ref]$null, [ref]$null)
$completerSbs = [System.Collections.Generic.List[object]]::new()
# Form 1: `Register-ArgumentCompleter -ScriptBlock {...}`
$astForPositions.FindAll({
    $a = $args[0]
    ($a -is [System.Management.Automation.Language.CommandAst]) -and
    $a.CommandElements -and
    ($a.CommandElements[0] -is [System.Management.Automation.Language.StringConstantExpressionAst]) -and
    ($a.CommandElements[0].Value -eq 'Register-ArgumentCompleter')
}, $true) | % {
    $sb = $_.CommandElements | ? {$_ -is [System.Management.Automation.Language.ScriptBlockExpressionAst]} | select -First 1
    if ($sb) {$completerSbs.Add($sb)}
}
# Form 2: `[ArgumentCompleter({...})]` parameter attribute
$astForPositions.FindAll({
    $a = $args[0]
    ($a -is [System.Management.Automation.Language.AttributeAst]) -and
    ($a.TypeName.Name -in @('ArgumentCompleter','ArgumentCompleterAttribute'))
}, $true) | % {
    $sb = $_.PositionalArguments | ? {$_ -is [System.Management.Automation.Language.ScriptBlockExpressionAst]} | select -First 1
    if ($sb) {$completerSbs.Add($sb)}
}
if ($completerSbs) {
    $thinInsertions = @()
    foreach ($sbArg in $completerSbs) {
        $sbAst = $sbArg.ScriptBlock
        $shimText = Build-ThinShim $sbAst
        if (!$shimText) {continue}
        # Insert after `param(...)` if the completer has one (param must be the first
        # statement in a scriptblock), else right after the opening `{`.
        $insertOffset = $sbAst.Extent.StartOffset + 1
        if ($sbAst.ParamBlock) {$insertOffset = $sbAst.ParamBlock.Extent.EndOffset}
        $thinInsertions += ,@{offset = $insertOffset; text = "`n$shimText"}
    }
    if ($thinInsertions) {
        Write-APL ">*","@Injecting thin shims into $($thinInsertions.Count) argument completer scriptblock(s)"
        # Apply in reverse-offset order so each insertion doesn't invalidate the
        # offsets of earlier (lower-offset) ones.
        $thinInsertions | Sort-Object {-[int]$_.offset} | % {
            $Data = $Data.Insert($_.offset, $_.text)
        }
    }
}

if (!$Injecter) {
    Write-APL ">*","No Functions or Aliases to add... Writing the file as is..."
} elseif ($Data -match "`n?\[CmdletBinding\(\)\] *`n" -and !$ForceLinearLayout) {
    Write-APL ">*","Detected Procedural Layout"
    $M = [Regex]::Match($Data,"(?i)(Begin|Process|End) *\{")
    if (!$M.success) {
        Write-APL ">>!","No Begin/Process/End Tags found... Please check that your code is runnable?"
        Write-APL ">>!","If you are sure it works, use ","!-ForceLinearLayout"," switch to force linear layout"
        exit 1
    } else {$Data = $Data.insert($M.Index+$M.Length,$Injecter)}
} else {
    Write-APL ">*","Detected Linear Layout",$(if ($ForceLinearLayout){"! (Forced)"}else {""})
    $M = [Regex]::Match($Data,"(?i)(`n|^)param *\(")
    if (!$M.success) {$Data = "$("$Injecter`n".TrimStart())$Data"} else {
        $i = 1;$dex=0;$InString=0
        foreach ($c in $Data[($M.Index+$M.Length)..$Data.Length]) {$dex++
            if ($Dbg) {Write-APL ">>*","Explored $c [Stack: $i |$Dex :: $InString -> $(('Code','Dbl-Quot','Single-Quot')[$InString])]"}
            if ($InString -ne 2 -and $c -eq """") {$InString=(1,0)[$InString]}
            elseif ($InString -ne 1 -and $c -eq "'") {$InString=(2,-1,0)[$InString]}
            elseif ($InString) {continue}
            if ($c -eq "(") {$i++}
            elseif ($c -eq ")") {if (!(--$i)) {break}}
        }
        $Data = $Data.insert($M.Index+$M.Length+$dex,$Injecter)
    }
}
Write-CompiledFile $Data
if ($PassThru) {return $code}
