<#
|==============================================================================>|
   AP-Compiler by APoorv Verma [AP] on 4/21/2014
|==============================================================================>|
    $) Compiles AP-Programs Independent of the AP-Modules file
    $) Reads And Calculates all the Modules needed!
    $) Adds code with comment in a neat BASE64 Code
    $) Has a blacklisting system
    $) Code layout detection
    $) Inject Point Detection
    $) AP-Compiler Forced Commands (ap-compiler: Write-AP,AP-Require)
    $) AST Based Function / Alias / Class Resolution (including forced commands)
    $) Remove Old Compiler Code
    $) AP-Compiler Debug Mode
    $) Highly performant lexical scanner
    $) Mini AP-Console Shim for AP-Console Functions
    $) Detailed Logging, verbose debugging
|==============================================================================>|
#>
[CmdletBinding(DefaultParameterSetName = 'Compile')]
param(
    [Parameter(Mandatory=$True, ParameterSetName='Compile', Position = 0)]
    [Parameter(Mandatory=$True, ParameterSetName='Uncompile', Position = 0)]
    [String]$File,
    [Parameter(ParameterSetName='Compile', Position = 1)][String]$OutputFolder = '.',
    [Parameter(ParameterSetName='Compile')][switch]$OverwriteSrc,
    [Parameter(ParameterSetName='Compile')][switch]$ForceLinearLayout,
    [Switch]$Dbg,
    [Parameter(ParameterSetName='Uncompile')][Alias('Uncompile')][Switch]$Strip,
    [Parameter(ParameterSetName='Compile')][Switch]$PassThru
)
# =======================================START=OF=COMPILER================================================================|
#    The Following Code was added by AP-Compiler 1.6 (APC: 1.3) To Make this program independent of AP-Core Engine
#    GitHub: https://github.com/avdaredevil/AP-Compiler
# ========================================================================================================================|
$Script:PSHell=$(if($PSHell){$PSHell}elseif($PSScriptRoot){$PSScriptRoot}else{"."});
if($AP_CONSOLE.mode -ne 'main' -or $AP_CONSOLE.customFlags.runAsCompiled) {
    $Script:AP_CONSOLE = [PsCustomObject]@{version=[version]'1.3'; mode = 'shim'; customFlags = @{}}
    function B64 {param([Parameter(ValueFromPipeline=$true)][String]$Text, [ValidateSet("UTF8","Unicode")][String]$Encoding = "UTF8")     [System.Text.Encoding]::$Encoding.GetString([System.Convert]::FromBase64String($Text))}
    # This syntax is to prevent AV's from misclassifying this as anything but innocuous
    & (Get-Alias iex) (B64 "ZnVuY3Rpb24gRmxhdHRlbiB7cGFyYW0oW29iamVjdFtdXSR4KQ0KDQogICAgaWYgKCEoJFggLWlzIFthcnJheV0pKSB7cmV0dXJuICR4fQ0KICAgIGlmICgkWC5jb3VudCAtZXEgMSkgew0KICAgICAgICByZXR1cm4gJHggfCAlIHskX30NCiAgICB9DQogICAgJHggfCAlIHtGbGF0dGVuICRffQ0KfQoKZnVuY3Rpb24gR2V0LUZpbGVFbmNvZGluZyB7cGFyYW0oW1BhcmFtZXRlcihNYW5kYXRvcnk9JFRydWUpXSRQYXRoKQ0KDQogICAgJGJ5dGVzID0gW2J5dGVbXV0oR2V0LUNvbnRlbnQgJFBhdGggLUFzQnl0ZVN0cmVhbSAtUmVhZENvdW50IDQgLVRvdGFsQ291bnQgNCkNCg0KICAgIGlmKCEkYnl0ZXMpIHtyZXR1cm4gJ3V0ZjgnfQ0KDQogICAgc3dpdGNoIC1yZWdleCAoJ3swOngyfXsxOngyfXsyOngyfXszOngyfScgLWYgJGJ5dGVzWzBdLCRieXRlc1sxXSwkYnl0ZXNbMl0sJGJ5dGVzWzNdKSB7DQogICAgICAgICdeZWZiYmJmJyAgIHtyZXR1cm4gJ3V0ZjgnfQ0KICAgICAgICAnXjJiMmY3NicgICB7cmV0dXJuICd1dGY3J30NCiAgICAgICAgJ15mZmZlJyAgICAge3JldHVybiAndW5pY29kZSd9DQogICAgICAgICdeZmVmZicgICAgIHtyZXR1cm4gJ2JpZ2VuZGlhbnVuaWNvZGUnfQ0KICAgICAgICAnXjAwMDBmZWZmJyB7cmV0dXJuICd1dGYzMid9DQogICAgICAgIGRlZmF1bHQgICAgIHtyZXR1cm4gJ2FzY2lpJ30NCiAgICB9DQp9CgpmdW5jdGlvbiBKUy1OQ1Ege2ZvcmVhY2ggKCRhIGluICRhcmdzKSB7JHIgPSBJbnZva2UtT3JSZXR1cm4gJGE7aWYgKCRudWxsIC1uZSAkcikge3JldHVybiAkcn19O3JldHVybiAkcn0KCmZ1bmN0aW9uIEdldC1Db2xvciB7DQogICAgPCMgIC5EZXNjcmlwdGlvbg0KICAgICAgICBGZXRjaGVzIGJhc2ljIGNvbG9ycyB1c2luZyB0aGUgVW5pY29kZSBFc2NhcGUgc2VxdWVuY2VzDQogICAgIz4NCiAgICBwYXJhbSAoDQogICAgICAgIFtWYWxpZGF0ZVNldCgNCiAgICAgICAgICAgICdyJywncmVzZXQnLCdyUycsJ3Jlc2V0U3R5bGVzJywnZCcsJ2RpbScsJ3MnLCdzdHJpa2UnLCd1JywndW5kZXJsaW5lJywnYicsJ2JvbGQnLCdpJywnaXRhbGljJywnYmwnLCdibGluaycsJ3JldmVyc2UnLCdoJywnaGlkZGVuJywNCiAgICAgICAgICAgICdCbGFjaycsJ0RhcmtCbHVlJywnRGFya0dyZWVuJywnRGFya0N5YW4nLCdEYXJrUmVkJywnRGFya01hZ2VudGEnLCdEYXJrWWVsbG93JywnR3JheScsJ0RhcmtHcmF5JywnQmx1ZScsJ0dyZWVuJywnQ3lhbicsJ1JlZCcsJ01hZ2VudGEnLCdZZWxsb3cnLCdXaGl0ZScsDQogICAgICAgICAgICAnYmcuQmxhY2snLCdiZy5EYXJrQmx1ZScsJ2JnLkRhcmtHcmVlbicsJ2JnLkRhcmtDeWFuJywnYmcuRGFya1JlZCcsJ2JnLkRhcmtNYWdlbnRhJywnYmcuRGFya1llbGxvdycsJ2JnLkdyYXknLCdiZy5EYXJrR3JheScsJ2JnLkJsdWUnLCdiZy5HcmVlbicsJ2JnLkN5YW4nLCdiZy5SZWQnLCdiZy5NYWdlbnRhJywnYmcuWWVsbG93JywnYmcuV2hpdGUnDQogICAgICAgICldW1N0cmluZ1tdXSRDb2RlLA0KICAgICAgICBbQWxpYXMoJ2JnJyldW1N3aXRjaF0kQmFja2dyb3VuZCwNCiAgICAgICAgW1N3aXRjaF0kQ29kZVN0cmluZw0KICAgICkNCiAgICBpZiAoJEFQX0NPTlNPTEUuY3VzdG9tRmxhZ3Mubm9Vbml4RXNjYXBlcykge3JldHVybn0NCiAgICAkQWxpYXNUYWJsZSA9IEB7dSA9ICd1bmRlcmxpbmUnO2IgPSAnYm9sZCc7aSA9ICdpdGFsaWMnO3IgPSAncmVzZXQnO3JTID0gJ3Jlc2V0U3R5bGVzJztzID0gJ3N0cmlrZSc7ZCA9ICdkaW0nO2JsID0gJ2JsaW5rJztoID0gJ2hpZGRlbid9DQogICAgaWYgKCEkR2xvYmFsOkFQX0NPTE9SX1RBQkxFKSB7DQogICAgICAgICRUQkwgPSAkR2xvYmFsOkFQX0NPTE9SX1RBQkxFID0gQHtyZXNldCA9IDA7Ym9sZCA9IDE7ZGltID0gMjtpdGFsaWMgPSAzO3VuZGVybGluZSA9IDQ7YmxpbmsgPSA1O3JldmVyc2UgPSA3O2hpZGRlbiA9IDg7c3RyaWtlID0gOTtyZXNldFN0eWxlcyA9ICcyMjsyMzsyNDsyNTsyNzsyODsyOSd9DQogICAgICAgIDAsMSB8ICUgew0KICAgICAgICAgICAgJEJnSW5kZXggPSAkXw0KICAgICAgICAgICAgMCwxIHwgJSB7DQogICAgICAgICAgICAgICAgJFNwY0luZGV4ID0gJF8NCiAgICAgICAgICAgICAgICAkaSA9IDANCiAgICAgICAgICAgICAgICAnQmxhY2suVHxSZWR8R3JlZW58WWVsbG93fEJsdWV8TWFnZW50YXxDeWFufFdoaXRlJy5zcGxpdCgnfCcpIHwgJSB7DQogICAgICAgICAgICAgICAgICAgICRJbmNyID0gJEJnSW5kZXggKiAxMA0KICAgICAgICAgICAgICAgICAgICAkQ29sTmFtZSA9ICgoJycsJ2JnLicpWyRCZ0luZGV4XSkrKCgnRGFyaycsJycpWyRTcGNJbmRleF0pKyRfDQogICAgICAgICAgICAgICAgICAgICRDb2xTcGFjZSA9ICgzMCwgOTApWyRTcGNJbmRleF0gKyAkSW5jcg0KICAgICAgICAgICAgICAgICAgICAkVEJMLiRDb2xOYW1lID0gJENvbFNwYWNlKygkaSsrKQ0KICAgICAgICAgICAgICAgIH0NCiAgICAgICAgICAgIH0NCiAgICAgICAgfQ0KICAgICAgICBAe0RhcmtHcmF5ID0gJ0JsYWNrLlQnO0JsYWNrID0gJ0RhcmtCbGFjay5UJztHcmF5ID0gJ0RhcmtXaGl0ZSd9LkdldEVudW1lcmF0b3IoKSB8ICUgew0KICAgICAgICAgICAgJFRCTC4oJF8uS2V5KSA9ICRUQkwuKCRfLlZhbHVlKQ0KICAgICAgICAgICAgJFRCTC4oJ2JnLicrJF8uS2V5KSA9ICRUQkwuKCdiZy4nKyRfLlZhbHVlKQ0KICAgICAgICAgICAgJFRCTC5yZW1vdmUoJF8uVmFsdWUpDQogICAgICAgICAgICAkVEJMLnJlbW92ZSgnYmcuJyskXy5WYWx1ZSkNCiAgICAgICAgfQ0KICAgIH0NCiAgICAkQ29kZXMgPSAoJENvZGUrJEFyZ3MgfCAlIHsNCiAgICAgICAgJEdsb2JhbDpBUF9DT0xPUl9UQUJMRS4oSlMtT1IgJEFsaWFzVGFibGUuJF8gJF8pDQogICAgfSkgLWpvaW4gJzsnDQogICAgaWYgKCRDb2RlU3RyaW5nKSB7cmV0dXJuICRDb2Rlc30NCiAgICByZXR1cm4gKEdldC1Fc2NhcGUpICsgJ1snICsgJENvZGVzICsgJ20nICMgVXNpbmcgc3RyaW5nIGNvbmNhdCBmb3IgZmFzdGVyIHByb2Nlc3NpbmcNCn0KCmZ1bmN0aW9uIEFQLUNvbnZlcnRQYXRoIHtwYXJhbShbUGFyYW1ldGVyKE1hbmRhdG9yeT0kVHJ1ZSldW1N0cmluZ10kUGF0aCkNCg0KICAgICRQYXRoU2VwID0gW0lPLlBhdGhdOjpEaXJlY3RvcnlTZXBhcmF0b3JDaGFyDQogICAgcmV0dXJuICRQYXRoIC1yZXBsYWNlDQogICAgICAgICI8RGVwPiIsIjxMaWI+JHtQYXRoU2VwfURlcGVuZGVuY2llcyIgLXJlcGxhY2UNCiAgICAgICAgIjxMaWI+IiwiPEhvbWU+JHtQYXRoU2VwfUFQLUxpYnJhcmllcyIgLXJlcGxhY2UNCiAgICAgICAgIjxDb21wKG9uZW50cyk/PiIsIjxIb21lPiR7UGF0aFNlcH1BUC1Db21wb25lbnRzIiAtcmVwbGFjZQ0KICAgICAgICAiPEhvbWU+IiwkUFNIZWxsfQoKZnVuY3Rpb24gQVAtUmVxdWlyZSB7cGFyYW0oW1BhcmFtZXRlcihNYW5kYXRvcnk9JFRydWUpXVtBbGlhcygiRnVuY3Rpb25hbGl0eSIsIkxpYnJhcnkiKV1bQXJndW1lbnRDb21wbGV0ZXIoew0KICAgIFtPdXRwdXRUeXBlKFtTeXN0ZW0uTWFuYWdlbWVudC5BdXRvbWF0aW9uLkNvbXBsZXRpb25SZXN1bHRdKV0NCiAgICBwYXJhbSgNCiAgICAgICAgW3N0cmluZ10gJENvbW1hbmROYW1lLA0KICAgICAgICBbc3RyaW5nXSAkUGFyYW1ldGVyTmFtZSwNCiAgICAgICAgW3N0cmluZ10gJFdvcmRUb0NvbXBsZXRlLA0KICAgICAgICBbU3lzdGVtLk1hbmFnZW1lbnQuQXV0b21hdGlvbi5MYW5ndWFnZS5Db21tYW5kQXN0XSAkQ29tbWFuZEFzdCwNCiAgICAgICAgW1N5c3RlbS5Db2xsZWN0aW9ucy5JRGljdGlvbmFyeV0gJEZha2VCb3VuZFBhcmFtZXRlcnMNCiAgICApDQogICAgJENvbXBsZXRpb25SZXN1bHRzID0gW1N5c3RlbS5Db2xsZWN0aW9ucy5HZW5lcmljLkxpc3RbU3lzdGVtLk1hbmFnZW1lbnQuQXV0b21hdGlvbi5Db21wbGV0aW9uUmVzdWx0XV06Om5ldygpDQogICAgJExpYiA9IEAoIkludGVybmV0Iiwib3M6d2luZG93cyIsIm9zOm1hYyIsIm9zOmxpbnV4Iiwib3M6dW5peCIsImFkbWluaXN0cmF0b3IiLCJyb290IiwiZGVwOiIsImxpYjoiLCJsaWJfdGVzdDoiLCJtb2R1bGU6IiwibW9kdWxlX3Rlc3Q6IiwiZnVuY3Rpb246Iiwic3RyaWN0X2Z1bmN0aW9uOiIsImFiaWxpdHk6ZXNjYXBlX2NvZGVzIiwiYWJpbGl0eTplbW9qaXMiLCJhYmlsaXR5Om5lcmRfZm9udCIsImFiaWxpdHk6bG9uZ19wYXRocyIsImFiaWxpdHk6Y29uc29sZV9tYW5pcHVsYXRpb24iKQ0KICAgICRqc09yID0ge2ZvcmVhY2ggKCRhIGluICRhcmdzKSB7JGEgPSAkKGlmKCRhIC1pcyBbc2NyaXB0YmxvY2tdKXsmJGF9ZWxzZXskYX0pO2lmICghJGEpe2NvbnRpbnVlfTtyZXR1cm4gJGF9O3JldHVybiAkYX0gIyBNYW51YWxseSBlbWJlZGRlZCBKUy1PUg0KICAgICYgJGpzT3IgeyRMaWIgfCA/IHskXyAtbGlrZSAiJFdvcmRUb0NvbXBsZXRlKiJ9fSB7JExpYiB8ID8geyRfIC1saWtlICIqJFdvcmRUb0NvbXBsZXRlKiJ9fSB8ICUgew0KICAgICAgICAkQ29tcGxldGlvblJlc3VsdHMuQWRkKFtTeXN0ZW0uTWFuYWdlbWVudC5BdXRvbWF0aW9uLkNvbXBsZXRpb25SZXN1bHRdOjpuZXcoJF8sICRfLCAnUGFyYW1ldGVyVmFsdWUnLCAkXykpDQogICAgfQ0KICAgIHJldHVybiAkQ29tcGxldGlvblJlc3VsdHMNCn0pXVtTdHJpbmddJExpYiwgW1NjcmlwdEJsb2NrXSRPbkZhaWwsIFtTd2l0Y2hdJFBhc3NUaHJ1KQ0KDQogICAgJExvYWRNb2R1bGUgPSB7DQogICAgICAgIHBhcmFtKCRGaWxlLFtib29sXSRJbXBvcnQpDQogICAgICAgIHRyeSB7SW1wb3J0LU1vZHVsZSAkRmlsZSAtZWEgc3RvcDtyZXR1cm4gMX0gY2F0Y2gge30NCiAgICAgICAgJExpYj1BUC1Db252ZXJ0UGF0aCAiPExJQj4iOyRMRiA9ICIkTGliXCRGaWxlIg0KICAgICAgICAkZiA9ICRMRiwiJExGLnBzbTEiLCIkTEYuZGxsIiB8ID8ge3Rlc3QtcGF0aCAtdCBsZWFmICRffSB8IHNlbGVjdCAtZiAxDQogICAgICAgIGlmICgkZiAtYW5kICRJbXBvcnQpIHsNCiAgICAgICAgICAgIEltcG9ydC1Nb2R1bGUgJGYNCiAgICAgICAgICAgIGlmICgkPykge3JldHVybiAkZn0gZWxzZSB7V3JpdGUtQVAgIiFGYWlsZWQgdG8gaW1wb3J0IFskRmlsZSAtPiAkRl0iO3JldHVybiAwfQ0KICAgICAgICB9DQogICAgICAgIHJldHVybiAkZg0KICAgIH0NCiAgICAkSW52b2tlT3JSZXR1cm4gPSB7cGFyYW0oJENtZCwgJGZhbGxiYWNrPTApIGlmICgkQ21kIC1pcyBbU2NyaXB0QmxvY2tdKSB7dHJ5eyYgJENtZH1jYXRjaHskZmFsbGJhY2t9fSBlbHNlIHskQ21kfX0NCiAgICBpZiAoISRPbkZhaWwpIHskUGFzc1RocnUgPSAkdHJ1ZX0NCiAgICAkU3RhdCA9ICQoc3dpdGNoIC1yZWdleCAoJExpYi50cmltKCkpIHsNCiAgICAgICAgIl5JbnRlcm5ldCQiICAgICAgICAgICAgICAgICAgICAgICB7dGVzdC1jb25uZWN0aW9uIGdvb2dsZS5jb20gLUNvdW50IDEgLVF1aWV0fQ0KICAgICAgICAiXmFkbWluKGlzdHJhdG9yKT8kfF5yb290JCIgICAgICAgIHtUZXN0LUFkbWluaXN0cmF0b3J9DQogICAgICAgICJeZGVwOiguKikkIiAgICAgICAgICAgICAgICAgICAgICAge0dldC1XaGVyZSAkTWF0Y2hlc1sxXX0NCiAgICAgICAgIl4obGlifG1vZHVsZSk6KC4qKSQiICAgICAgICAgICAgICB7JExvYWRNb2R1bGUuaW52b2tlKCRNYXRjaGVzWzJdLCAkdHJ1ZSl9DQogICAgICAgICJeKGxpYnxtb2R1bGUpX3Rlc3Q6KC4qKSQiICAgICAgICAgeyRMb2FkTW9kdWxlLmludm9rZSgkTWF0Y2hlc1syXSl9DQogICAgICAgICJeZnVuY3Rpb246KC4qKSQiICAgICAgICAgICAgICAgICAge2djbSAkTWF0Y2hlc1sxXSAtZWEgU2lsZW50bHlDb250aW51ZX0NCiAgICAgICAgIl5zdHJpY3RfZnVuY3Rpb246KC4qKSQiICAgICAgICAgICB7VGVzdC1QYXRoICJGdW5jdGlvbjpcJCgkTWF0Y2hlc1sxXSkifQ0KICAgICAgICAiXm9zOih3aW4oZG93cyk/fGxpbnV4fG1hY3x1bml4KSQiIHskbyA9IEdldC1PUzskSXNVbml4ID0gJFBTVmVyc2lvblRhYmxlLlBsYXRmb3JtIC1lcSAiVW5peCI7c3dpdGNoIC1yZWdleCAoJE1hdGNoZXNbMV0pIHsNCiAgICAgICAgICAgICJed2luIiAgIHtyZXR1cm4gJG8gLWVxICJXaW5kb3dzIn0NCiAgICAgICAgICAgICJsaW51eCIgIHtyZXR1cm4gJG8gLWVxICJMaW51eCJ9DQogICAgICAgICAgICAibWFjIiAgICB7cmV0dXJuICRvIC1lcSAiTWFjT1MifQ0KICAgICAgICAgICAgInVuaXgiICAge3JldHVybiAkSXNVbml4fQ0KICAgICAgICB9fQ0KICAgICAgICAiXmFiaWxpdHk6KC4rKSQiICAgICB7JG0gPSAkTWF0Y2hlc1sxXTtKUy1OQ1EgKCYgJEludm9rZU9yUmV0dXJuIChAew0KICAgICAgICAgICAgZXNjYXBlX2NvZGVzID0gJEhvc3QuVUkuU3VwcG9ydHNWaXJ0dWFsVGVybWluYWwNCiAgICAgICAgICAgIGVtb2ppcyA9ICRlbnY6V1RfU0VTU0lPTiAtb3IgJGVudjpXVF9QUk9GSUxFX0lEIC1vciAoJGVudjpURVJNX1BST0dSQU0gLW1hdGNoICd2c2NvZGV8aVRlcm0uYXBwfEFwcGxlX1Rlcm1pbmFsJykNCiAgICAgICAgICAgIG5lcmRfZm9udCA9IHskcD0kSG9zdC5VSS5SYXdVSS5DdXJzb3JQb3NpdGlvbjtXcml0ZS1Ib3N0IC1Ob05ld2xpbmUgKFtjaGFyXTo6Q29udmVydEZyb21VdGYzMigweEYwNTMxKSk7JG49JEhvc3QuVUkuUmF3VUkuQ3Vyc29yUG9zaXRpb247JEhvc3QuVUkuUmF3VUkuQ3Vyc29yUG9zaXRpb249JHA7V3JpdGUtSG9zdCAtTm9OZXdsaW5lICcgICc7JEhvc3QuVUkuUmF3VUkuQ3Vyc29yUG9zaXRpb249JHA7KCRuLlgtJHAuWCktZXEgMX0NCiAgICAgICAgICAgIGxvbmdfcGF0aHMgPSAkUFNWZXJzaW9uVGFibGUuUGxhdGZvcm0gLWVxICJVbml4IiAtb3IgKEdldC1JdGVtUHJvcGVydHkgLVBhdGggIkhLTE06XFNZU1RFTVxDdXJyZW50Q29udHJvbFNldFxDb250cm9sXEZpbGVTeXN0ZW0iIHwgJSBsb25ncGF0aHNlbmFibGVkKQ0KICAgICAgICAgICAgY29uc29sZV9tYW5pcHVsYXRpb24gPSAhW1N5c3RlbS5Db25zb2xlXTo6SXNPdXRwdXRSZWRpcmVjdGVkIC1hbmQgKCRIb3N0Lk5hbWUgLWVxICdDb25zb2xlSG9zdCcpDQogICAgICAgIH1bJG1dKSkge1dyaXRlLUFQICIhUmVxdWlyZWQgYWJpbGl0eSBbJG1dIGlzIG5vdCBzdXBwb3J0ZWQgb24gdGhpcyBwbGF0Zm9ybS4iOyB0aHJvdyAnQkFEX1NFTEVDVE9SJ319DQogICAgICAgIGRlZmF1bHQge1dyaXRlLUFQICIhSW52YWxpZCBzZWxlY3RvciBwcm92aWRlZCBbJCgiJExpYiIuc3BsaXQoJzonKVswXSldIjt0aHJvdyAnQkFEX1NFTEVDVE9SJ30NCiAgICB9KQ0KICAgIGlmICghJFN0YXQgLWFuZCAkT25GYWlsKSB7JiAkT25GYWlsfQ0KICAgIGlmICgkUGFzc1RocnUgLW9yICEkT25GYWlsKSB7cmV0dXJuICRTdGF0fQ0KfQoKZnVuY3Rpb24gV3JpdGUtQVAgew0KICAgIFtDbWRsZXRCaW5kaW5nKCldDQogICAgcGFyYW0oW1BhcmFtZXRlcihWYWx1ZUZyb21QaXBlbGluZT0xLCBNYW5kYXRvcnk9MSldJFRleHQsW1N3aXRjaF0kTm9TaWduLFtTd2l0Y2hdJFBsYWluVGV4dCxbVmFsaWRhdGVTZXQoIkNlbnRlciIsIlJpZ2h0IiwiTGVmdCIpXVtTdHJpbmddJEFsaWduPSdMZWZ0JyxbU3dpdGNoXSRQYXNzVGhydSkNCiAgICBiZWdpbiB7JFRUID0gQCgpfQ0KICAgIFByb2Nlc3MgeyRUVCArPSAsJFRleHR9DQogICAgRU5EIHsNCiAgICAgICAgJEJsdWUgPSAkKGlmICgkQVBfQ09OU09MRS5jdXN0b21GbGFncy5sZWdhY3lDb2xvcnMpezN9ZWxzZXsnQmx1ZSd9KQ0KICAgICAgICBpZiAoJFRULmNvdW50IC1lcSAxKSB7JFRUID0gJFRUWzBdfTskVGV4dCA9ICRUVA0KICAgICAgICBpZiAoJHRleHQuY291bnQgLWd0IDEgLW9yICR0ZXh0LkdldFR5cGUoKS5OYW1lIC1tYXRjaCAiXFtcXSQiKSB7DQogICAgICAgICAgICByZXR1cm4gJFRleHQgfCAlIHsNCiAgICAgICAgICAgICAgICBXcml0ZS1BUCAkXyAtTm9TaWduOiROb1NpZ24gLVBsYWluVGV4dDokUGxhaW5UZXh0IC1BbGlnbiAkQWxpZ24gLVBhc3NUaHJ1OiRQYXNzVGhydQ0KICAgICAgICAgICAgfQ0KICAgICAgICB9DQogICAgICAgIGlmICghJHRleHQgLW9yICR0ZXh0IC1ub3RtYXRjaCAiKD9zbWkpXigoPzxOTkw+eCl8KD88TlM+bnM/KSl7MCwyfSg/PHQ+XD4qKSg/PHM+W1wrXC1cIVwqXCNcQF9dKSg/PHc+LiopIikge3JldHVybiBBbGlnbi1UZXh0ICRUZXh0IC1BbGlnbiAkQWxpZ24gfCBXcml0ZS1Ib3N0fQ0KICAgICAgICAkdGIgID0gIiAgICAiKiRNYXRjaGVzLnQubGVuZ3RoDQogICAgICAgICRDb2wgPSBAeycrJz0nMic7Jy0nPScxMic7JyEnPScxNCc7JyonPSRCbHVlOycjJz0nRGFya0dyYXknOydAJz0nR3JheSc7J18nPSd3aGl0ZSd9WygkU2lnbiA9ICRNYXRjaGVzLlMpXQ0KICAgICAgICBpZiAoISRDb2wpIHtUaHJvdyAiSW5jb3JyZWN0IFNpZ24gWyRTaWduXSBQYXNzZWQhIn0NCiAgICAgICAgJFNpZ24gPSAkKGlmICgkTm9TaWduIC1vciAkTWF0Y2hlcy5OUykgeyIifSBlbHNlIHsiWyRTaWduXSAifSkNCiAgICAgICAgJERhdGEgPSAiJHRiJFNpZ24kKCRNYXRjaGVzLlcpIjtpZiAoISREYXRhKSB7cmV0dXJuIFdyaXRlLUhvc3QgIiJ9DQogICAgICAgIGlmIChBUC1SZXF1aXJlICJmdW5jdGlvbjpBbGlnbi1UZXh0IiAtcGEpIHsNCiAgICAgICAgICAgICREYXRhID0gQWxpZ24tVGV4dCAtQWxpZ24gJEFsaWduICIkdGIkU2lnbiQoJE1hdGNoZXMuVykiDQogICAgICAgIH0NCiAgICAgICAgaWYgKCRQbGFpblRleHQpIHtyZXR1cm4gJERhdGF9DQogICAgICAgICREYXRhTGluZXMgPSAkRGF0YSAtc3BsaXQgImBuIg0KICAgICAgICAxLi4kRGF0YUxpbmVzLkNvdW50IHwgJSB7DQogICAgICAgICAgICAkSWR4ID0gJF8gLSAxDQogICAgICAgICAgICAkTk5MID0gISRpZHggLWFuZCAkTWF0Y2hlcy5OTkwNCiAgICAgICAgICAgIFdyaXRlLUhvc3QgLU5vTmV3TGluZTokTk5MIC1mICRDb2wgJERhdGFMaW5lc1skSWR4XQ0KICAgICAgICAgICAgaWYgKCRQYXNzVGhydSkge3JldHVybiAkRGF0YX0NCiAgICAgICAgfQ0KICAgIH0NCn0KCmZ1bmN0aW9uIFN0cmlwLUNvbG9yQ29kZXMgew0KICAgIFtDbWRsZXRCaW5kaW5nKCldcGFyYW0oW1BhcmFtZXRlcihWYWx1ZUZyb21QaXBlbGluZT0xKV0kU3RyKQ0KICAgIHByb2Nlc3MgeyRTdHIgfCAlIHskXyAtcmVwbGFjZSAiJChbcmVnZXhdOjplc2NhcGUoIiQoR2V0LUVzY2FwZSlbIikpXGQrKFw7XGQrKSptIiwiIn19DQp9CgpmdW5jdGlvbiBDb252ZXJ0LVRvQmFzZTY0IHtwYXJhbShbUGFyYW1ldGVyKFZhbHVlRnJvbVBpcGVsaW5lPSR0cnVlKV1bU3RyaW5nXSRUZXh0LCBbVmFsaWRhdGVTZXQoIlVURjgiLCJVbmljb2RlIildW1N0cmluZ10kRW5jb2RpbmcgPSAiVVRGOCIpDQoNCiAgICBbU3lzdGVtLkNvbnZlcnRdOjpUb0Jhc2U2NFN0cmluZyhbU3lzdGVtLlRleHQuRW5jb2RpbmddOjokRW5jb2RpbmcuR2V0Qnl0ZXMoJFRleHQpKQ0KfQoKZnVuY3Rpb24gSlMtT1Ige2ZvcmVhY2ggKCRhIGluICRhcmdzKSB7JHIgPSBJbnZva2UtT3JSZXR1cm4gJGE7aWYgKCEkcil7Y29udGludWV9O3JldHVybiAkcn07cmV0dXJuICRyfQoKZnVuY3Rpb24gV3JpdGUtQVBMIHsNCiAgICBbQ21kbGV0QmluZGluZygpXQ0KICAgIHBhcmFtKA0KICAgICAgICBbUGFyYW1ldGVyKFZhbHVlRnJvbVBpcGVsaW5lPSR0cnVlLCBNYW5kYXRvcnk9JFRydWUpXSRUZXh0LA0KICAgICAgICBbQWxpYXMoJ05TJyldW1N3aXRjaF0kTm9TaWduLA0KICAgICAgICBbQWxpYXMoJ05OTCcsJ05MJyldW1N3aXRjaF0kTm9OZXdMaW5lLA0KICAgICAgICBbU3dpdGNoXSRQYXNzVGhydQ0KICAgICkNCiAgICBiZWdpbiB7DQogICAgICAgICRTaWduUmd4ID0gIltcK1wtXCFcKlwjXEBfXSI7ICRUVCA9IEAoKQ0KICAgICAgICAkSXNWZXJib3NlID0gJFBTQ21kbGV0Lk15SW52b2NhdGlvbi5Cb3VuZFBhcmFtZXRlcnMuVmVyYm9zZQ0KICAgIH0NCiAgICBwcm9jZXNzIHtGbGF0dGVuICRUZXh0IHwgJSB7DQogICAgICAgICRMaW5lID0gJF8gLXNwbGl0ICJgbiINCiAgICAgICAgJExpbmVTeW1ib2wgPSAkKGlmICgkbGluZVswXSAtbWF0Y2ggIl5uP3g/bj8oXD4qKSgkU2lnblJneCkuKiQiKSB7JE1hdGNoZXNbMl19IGVsc2UgeyIifSkNCiAgICAgICAgaWYgKCRJc1ZlcmJvc2UpIHtXcml0ZS1WZXJib3NlICIkKGNvbCBpKUxpbmVTeW1ib2w6ICRMaW5lU3ltYm9sIHwgTGluZTogJExpbmUkKGNvbCByUykifQ0KICAgICAgICAxLi4kTGluZS5MZW5ndGggfCAlIHsNCiAgICAgICAgICAgICRpZHggPSAkXyAtIDENCiAgICAgICAgICAgIGlmICgkaWR4KSB7JFRUICs9ICJgbiIrJExpbmVTeW1ib2wrJExpbmVbJGlkeF19DQogICAgICAgICAgICBlbHNlIHskVFQgKz0gJExpbmVbJGlkeF19DQogICAgICAgIH0NCiAgICB9fQ0KICAgIGVuZCB7DQogICAgICAgIGlmICgkSXNWZXJib3NlKSB7V3JpdGUtVmVyYm9zZSAiJChjb2wgaSkkKFByaW50LUxpc3QgJFRUKSQoY29sIHJTKSJ9DQogICAgICAgIGZvciAoJGk9MDskaSAtbHQgJFRULmNvdW50OyRpKyspIHsNCiAgICAgICAgICAgIFtzdHJpbmddJENodW5rID0gJFRUWyRpXQ0KICAgICAgICAgICAgaWYgKCRDaHVua1swXSAtZXEgImBuIikgeyRDaHVuayA9ICRDaHVuay5TdWJzdHJpbmcoMSk7V3JpdGUtSG9zdH0gIyBTcGVjaWFsIGNhc2UgZm9yIG5ldyBsaW5lIHZpYSBgbg0KICAgICAgICAgICAgJENodW5rID0gJENodW5rIC1yZXBsYWNlICJebj94P24/KFw+KiRTaWduUmd4KSIsJyQxJw0KICAgICAgICAgICAgaWYgKCRDaHVuayAtbm90bWF0Y2ggIl5cPiokU2lnblJneC4qIikgeyRDaHVuayA9ICJfJENodW5rIn0gIyBVc2UgZGVmYXVsdCBhcyB3aGl0ZQ0KICAgICAgICAgICAgJFByZWZpeENvZGUgPSA/OiAoJGkgLWVxIDApIHsieCQoPzogJE5vU2lnbiB7J24nfSB7Jyd9KSJ9IHs/OiAoJGkgLW5lICgkVFQuQ291bnQgLSAxKSkgeyJueCJ9ICJuJCg/OiAkTm9OZXdMaW5lIHsneCd9IHsnJ30pIn0NCiAgICAgICAgICAgIGlmICgkVFQuQ291bnQgLWVxIDEpIHskUHJlZml4Q29kZSA9ICIkKD86ICROb1NpZ24geyduJ30geycnfSkkKD86ICROb05ld0xpbmUgeyd4J30geycnfSkifQ0KICAgICAgICAgICAgaWYgKCRJc1ZlcmJvc2UpIHtXcml0ZS1WZXJib3NlICIkKGNvbCBpKVByZWZpeENvZGU6ICRQcmVmaXhDb2RlIHwgQ2h1bms6ICRDaHVuayQoY29sIHJTKSJ9DQogICAgICAgICAgICBXcml0ZS1BUCAiJFByZWZpeENvZGUkQ2h1bmsiIC1QYXNzVGhydTokUGFzc1RocnUNCiAgICAgICAgfQ0KICAgIH0NCn0KCmZ1bmN0aW9uIEdldC1Fc2NhcGUgew0KICAgIGlmICgkbnVsbCAtZXEgJEFQX0NPTlNPTEUuY3VzdG9tRmxhZ3MuX19kZXRlY3RlZF9lc2NhcGVfY29kZXMpIHskQVBfQ09OU09MRS5jdXN0b21GbGFncy5fX2RldGVjdGVkX2VzY2FwZV9jb2RlcyA9IEFQLVJlcXVpcmUgImFiaWxpdHk6ZXNjYXBlX2NvZGVzIn0NCiAgICBpZiAoISRBUF9DT05TT0xFLmN1c3RvbUZsYWdzLl9fZGV0ZWN0ZWRfZXNjYXBlX2NvZGVzIC1hbmQgISRBUF9DT05TT0xFLmN1c3RvbUZsYWdzLmZvcmNlVW5peEVzY2FwZXMpIHt0aHJvdyAiW0FQQ29uc29sZTo6R2V0LUVzY2FwZV0gWW91ciBjb25zb2xlIGRvZXMgbm90IHN1cHBvcnQgQU5TSSBlc2NhcGUgY29kZXMuIFlvdSBjYW4gc2V0IGAkQVBfQ09OU09MRS5jdXN0b21GbGFncy5ub1VuaXhFc2NhcGVzID0gYCR0cnVlIHRvIGRpc2FibGUgdW5peCBlc2NhcGUgY29kZXMuIE9yLCB1c2U6IGAkQVBfQ09OU09MRS5jdXN0b21GbGFncy5mb3JjZVVuaXhFc2NhcGVzIHRvIGF0dGVtcHQgaXQgYW55d2F5cyJ9DQogICAgIyBXZSBkbyB0aGlzLCBiZWNhdXNlIFBvd2VyU2hlbGwgTmF0aXZlIGRvZXNuJ3Qga25vdyBgZQ0KICAgIHJldHVybiBbQ2hhcl0weDFiICMgYGUNCn0KCmZ1bmN0aW9uIEdldC1PUyB7DQogICAgaWYgKCRQU1ZlcnNpb25UYWJsZS5QU0VkaXRpb24gLWVxICdDb3JlJykgew0KICAgICAgICBpZiAoJElzV2luZG93cykge3JldHVybiAnV2luZG93cyd9DQogICAgICAgIGVsc2VpZiAoJElzTGludXgpIHtyZXR1cm4gJ0xpbnV4J30NCiAgICAgICAgZWxzZWlmICgkSXNNYWNPUykge3JldHVybiAnTWFjT1MnfQ0KICAgIH0gZWxzZSB7cmV0dXJuICdXaW5kb3dzJ30NCn0KCmZ1bmN0aW9uIEdldC1QYXRoIHtwYXJhbSgkbWF0Y2gsIFtzdHJpbmddJFBhdGhWYXIgPSAiUEFUSCIsIFtzdHJpbmddJFBhdGhTZXAgPSAiIikNCg0KICAgICRQdGggPSBbRW52aXJvbm1lbnRdOjpHZXRFbnZpcm9ubWVudFZhcmlhYmxlKCRQYXRoVmFyKQ0KICAgICRQYXRoU2VwID0gR2V0LVBhdGhWYXJTZXAgJFBhdGhTZXANCiAgICBpZiAoISRQdGgpIHtyZXR1cm4gQCgpfQ0KICAgIFNldC1QYXRoICRQdGggLVBhdGhWYXIgJFBhdGhWYXIgLVBhdGhTZXAgJFBhdGhTZXANCiAgICAkZCA9ICgkUHRoKS5zcGxpdCgkUGF0aFNlcCkNCiAgICBpZiAoJG1hdGNoKSB7JGQgLW1hdGNoICRtYXRjaH0gZWxzZSB7JGR9DQp9CgpmdW5jdGlvbiBQcmludC1MaXN0IHtwYXJhbSgkeCwgW1N3aXRjaF0kSW5SZWN1cnNlKQ0KDQogICAgaWYgKCR4LmNvdW50IC1sZSAxKSB7cmV0dXJuID86KCRJblJlY3Vyc2UpeyR4fXsiWyR4XSJ9fSBlbHNlIHsNCiAgICAgICAgcmV0dXJuICJbJCgoJHggfCAlIHtQcmludC1MaXN0ICRfIC1JblJlY3Vyc2V9KSAtam9pbiAnLCAnKV0iDQogICAgfQ0KfQoKZnVuY3Rpb24gU2V0LVBhdGggew0KICAgIFtjbWRsZXRiaW5kaW5nKCldDQogICAgcGFyYW0oDQogICAgICAgIFtQYXJhbWV0ZXIoTWFuZGF0b3J5ID0gJHRydWUsIFZhbHVlRnJvbVBpcGVsaW5lID0gJHRydWUpXVtzdHJpbmdbXV0kUGF0aCwNCiAgICAgICAgW3N0cmluZ10kUGF0aFNlcCwNCiAgICAgICAgW3N0cmluZ10kUGF0aFZhciA9ICJQQVRIIg0KICAgICkNCiAgICBiZWdpbiB7DQogICAgICAgIFtzdHJpbmdbXV0kRmluYWxQYXRoDQogICAgICAgICRQYXRoU2VwID0gR2V0LVBhdGhWYXJTZXAgJFBhdGhTZXANCiAgICB9DQogICAgcHJvY2VzcyB7DQogICAgICAgICRQYXRoIHwgJSB7DQogICAgICAgICAgICAkRmluYWxQYXRoICs9ICRfDQogICAgICAgIH0NCiAgICB9DQogICAgZW5kIHsNCiAgICAgICAgJFB0aCA9ICRGaW5hbFBhdGggLWpvaW4gJFBhdGhTZXANCiAgICAgICAgJFB0aCA9ICgkUHRoIC1yZXBsYWNlKCIkUGF0aFNlcCsiLCAkUGF0aFNlcCkgLXJlcGxhY2UoIlxcJFBhdGhTZXB8XFwkIiwgJFBhdGhTZXApKS50cmltKCRQYXRoU2VwKQ0KICAgICAgICAkUHRoID0gKCgkUHRoKS5zcGxpdCgkUGF0aFNlcCkgfCBzZWxlY3QgLXVuaXF1ZSkgLWpvaW4gJFBhdGhTZXANCiAgICAgICAgW0Vudmlyb25tZW50XTo6U2V0RW52aXJvbm1lbnRWYXJpYWJsZSgkUGF0aFZhciwgJFB0aCkNCiAgICB9DQp9CgpmdW5jdGlvbiBQcm9jZXNzLVVuaWNvZGUgew0KICAgICRGaW5hbEFyZ3MgPSBGbGF0dGVuICRhcmdzDQogICAgIyBQb3dlclNoZWxsIENvcmUgc3ludGF4IHdoZW4gcHJvY2Vzc2VkIGJ5IFBvd2VyU2hlbGwgTmF0aXZlDQogICAgaWYgKCIkRmluYWxBcmdzIiAtbWF0Y2ggInV7KFx3Kyl9Iikgew0KICAgICAgICByZXR1cm4gW1JlZ2V4XTo6VW5lc2NhcGUoKCIkRmluYWxBcmdzIiAtcmVwbGFjZSAidXsoXHcrKX0iLCdcdSQxJykpDQogICAgfQ0KICAgIGlmICghKCRGaW5hbEFyZ3MgfCA/IHskXyAtaXNub3QgW2ludF19KSkgew0KICAgICAgICByZXR1cm4gW2NoYXJbXV0kRmluYWxBcmdzIC1qb2luICcnDQogICAgfQ0KICAgIHJldHVybiAkYXJncw0KfQoKZnVuY3Rpb24gR2V0LVBhdGhWYXJTZXAge3BhcmFtKFtzdHJpbmddJE92ZXJyaWRlID0gIiIpDQoNCiAgICAkSXNVbml4ID0gJFBTVmVyc2lvblRhYmxlLlBsYXRmb3JtIC1lcSAiVW5peCINCiAgICByZXR1cm4gSlMtT1IgJE92ZXJyaWRlICg/OiAkSXNVbml4ICI6IiAiOyIpDQp9CgpmdW5jdGlvbiBJbnZva2UtVGVybmFyeSB7cGFyYW0oJGRlY2lkZXIsICRpZnRydWUsICRpZmZhbHNlID0ge30pDQoNCiAgICAkSW52b2tlT3JSZXR1cm4gPSB7DQogICAgICAgIHBhcmFtKCRDbWQpDQogICAgICAgIGlmICgkQ21kIC1pcyBbU2NyaXB0QmxvY2tdKSB7JiAkQ21kfSBlbHNlIHskQ21kfQ0KICAgIH0NCiAgICBpZiAoJGRlY2lkZXIpIHsmICRJbnZva2VPclJldHVybiAkaWZ0cnVlfSBlbHNlIHsmICRJbnZva2VPclJldHVybiAkaWZmYWxzZX0NCn0KCmZ1bmN0aW9uIEFsaWduLVRleHQgew0KICAgIFtDbWRsZXRCaW5kaW5nKCldDQogICAgW091dHB1dFR5cGUoW1N0cmluZ10sIFtIYXNodGFibGVdKV0NCiAgICBwYXJhbSgNCiAgICAgICAgW1BhcmFtZXRlcihNYW5kYXRvcnk9MSwgVmFsdWVGcm9tUGlwZWxpbmU9MSldW0FsbG93RW1wdHlTdHJpbmcoKV1bU3RyaW5nW11dJFRleHQsDQogICAgICAgIFtzd2l0Y2hdJENvbG9yQ29kZXNEaXNjcmV0ZVBlckxpbmUsDQogICAgICAgIFtzd2l0Y2hdJFBvcmNlbGFpbiwNCiAgICAgICAgIyBUaGlzIGNhbiBiZSBbaW50XSBvciBbc2NyaXB0YmxvY2tdDQogICAgICAgICRDb25zdHJhaW5Ub1dpZHRoLA0KICAgICAgICBbVmFsaWRhdGVTZXQoIkNlbnRlciIsIlJpZ2h0IiwiTGVmdCIpXVtTdHJpbmddJEFsaWduPSdDZW50ZXInDQogICAgKQ0KICAgIGJlZ2luIHsNCiAgICAgICAgJGlzVmVyYm9zZSA9ICRQU0NtZGxldC5NeUludm9jYXRpb24uQm91bmRQYXJhbWV0ZXJzLlZlcmJvc2UNCiAgICAgICAgJEVzY2FwZUNvZGVTcGxpdHRlciA9ICIkKFtyZWdleF06OmVzY2FwZSgiJChHZXQtRXNjYXBlKVsiKSlcZCsoPzpcO1xkKykqbSINCiAgICAgICAgJERpdmlkZXJzID0gQHtjaHVuayA9IFByb2Nlc3MtVW5pY29kZSAiYHV7MTEyODh9Ijsgc3R5bGUgPSBQcm9jZXNzLVVuaWNvZGUgImB1ezEyMjg4fSJ9DQogICAgICAgICRGaW5hbEZvcm1hdHRlciA9IHsNCiAgICAgICAgICAgIHBhcmFtKCRMaW5lcywgJFN0eWxlcykNCiAgICAgICAgICAgIGlmICghJFBvcmNlbGFpbikge3JldHVybiAkTGluZXN9DQogICAgICAgICAgICBpZiAoJG51bGwgLWVxICRTdHlsZXMpIHskU3R5bGVzID0gW1JlZ2V4XTo6TWF0Y2hlcygoJExpbmVzIC1qb2luICIiKSwgJEVzY2FwZUNvZGVTcGxpdHRlcikudmFsdWV9DQogICAgICAgICAgICByZXR1cm4gQHtMaW5lcyA9ICRMaW5lczsgUnVubmluZ1N0eWxlcyA9ICRTdHlsZXN9DQogICAgICAgIH0NCiAgICB9DQogICAgcHJvY2VzcyB7DQogICAgICAgIGlmICgkQWxpZ24gLWVxICJMZWZ0Iikge3JldHVybiAmICRGaW5hbEZvcm1hdHRlciAkVGV4dH0NCiAgICAgICAgaWYgKCEiJFRleHQiLnRyaW0oKSkge3JldHVybiAkVGV4dH0NCiAgICAgICAgJFdpblNpemUgPSA/OiAkQ29uc3RyYWluVG9XaWR0aCB7SW52b2tlLU9yUmV0dXJuICRDb25zdHJhaW5Ub1dpZHRofSAoW2NvbnNvbGVdOjpCdWZmZXJXaWR0aCkNCiAgICAgICAgDQogICAgICAgICRUZXh0ID0gJFRleHQgLXNwbGl0ICJgcj9gbiINCiAgICAgICAgaWYgKCRUZXh0LmNvdW50IC1ndCAxKSB7DQogICAgICAgICAgICAkTGluZXMgPSAkVGV4dCB8IEFsaWduLVRleHQgLUFsaWduICRBbGlnbiAtQ29sb3JDb2Rlc0Rpc2NyZXRlUGVyTGluZTokQ29sb3JDb2Rlc0Rpc2NyZXRlUGVyTGluZSAtUG9yY2VsYWluDQogICAgICAgICAgICBpZiAoJENvbG9yQ29kZXNEaXNjcmV0ZVBlckxpbmUpIHsNCiAgICAgICAgICAgICAgICBmb3IgKCRpID0gMTsgJGkgLWx0ICRMaW5lcy5Db3VudDsgJGkrKykgew0KICAgICAgICAgICAgICAgICAgICAkTGluZSA9ICRMaW5lc1skaV0NCiAgICAgICAgICAgICAgICAgICAgJFByZXZTdHlsZXMgKz0gJExpbmVzWyRpIC0gMV0uUnVubmluZ1N0eWxlcw0KICAgICAgICAgICAgICAgICAgICAkTGluZS5MaW5lcyA9ICRMaW5lLkxpbmVzIHwgJSB7IiRQcmV2U3R5bGVzJF8ifQ0KICAgICAgICAgICAgICAgICAgICAkTGluZS5SdW5uaW5nU3R5bGVzID0gIiRQcmV2U3R5bGVzJCgkTGluZS5SdW5uaW5nU3R5bGVzKSINCiAgICAgICAgICAgICAgICB9DQogICAgICAgICAgICB9DQogICAgICAgICAgICByZXR1cm4gJiAkRmluYWxGb3JtYXR0ZXIgKEZsYXR0ZW4gJExpbmVzLkxpbmVzKSAoJExpbmVzLlJ1bm5pbmdTdHlsZXMgLWpvaW4gIiIpDQogICAgICAgIH0NCiAgICAgICAgIyBTaW5nbGUgbm9uIGBuIGxpbmUgcHJvY2Vzcw0KICAgICAgICAkQ2xlYW5UZXh0U2l6ZSA9IChTdHJpcC1Db2xvckNvZGVzICgiIiskVGV4dCkpLkxlbmd0aA0KDQogICAgICAgICMgPT09PT09PT0gTGluZSBpcyA8ICRXaW5TaXplID09PT09PT09PT09PT09fA0KICAgICAgICBpZiAoJENsZWFuVGV4dFNpemUgLWxlICRXaW5TaXplKSB7DQogICAgICAgICAgICBpZiAoJEFsaWduIC1lcSAiQ2VudGVyIikgew0KICAgICAgICAgICAgICAgIHJldHVybiAmICRGaW5hbEZvcm1hdHRlciAoIiAiKlttYXRoXTo6dHJ1bmNhdGUoKCRXaW5TaXplLSRDbGVhblRleHRTaXplKS8yKSskVGV4dCkNCiAgICAgICAgICAgIH0NCiAgICAgICAgICAgICMgUmlnaHQNCiAgICAgICAgICAgIHJldHVybiAmICRGaW5hbEZvcm1hdHRlciAoIiAiKigkV2luU2l6ZS0kQ2xlYW5UZXh0U2l6ZSkrJFRleHQpDQogICAgICAgIH0NCg0KICAgICAgICAjID09PT09PT09IExpbmUgaXMgPj0gJFdpblNpemUgPT09PT09PT09PT09PT18DQogICAgICAgICMgVHJhY2tpbmcgU3R5bGVzDQogICAgICAgICRSdW5uaW5nU3R5bGVzID0gIiINCiAgICAgICAgJEN1cnJsaW5lID0gQHsNCiAgICAgICAgICAgIHN0eWxlZERhdGEgPSAiIg0KICAgICAgICAgICAgY29udGVudFNpemUgPSAwDQogICAgICAgICAgICBmaW5hbExpbmVzID0gQCgpDQogICAgICAgICAgICBuZXh0ID0gew0KICAgICAgICAgICAgICAgICMgV3JpdGUtVmVyYm9zZSAiKiRJbnZvayB8IE5ldyBMaW5lIHwgTGluZURhdGE6ICQoKCcnKyRDdXJybGluZS5zdHlsZWREYXRhLkxlbmd0aCkuUGFkTGVmdCgzKSkiDQogICAgICAgICAgICAgICAgJEN1cnJsaW5lLmZpbmFsTGluZXMgKz0gLCRDdXJybGluZS5zdHlsZWREYXRhDQogICAgICAgICAgICAgICAgJEN1cnJsaW5lLnN0eWxlZERhdGEgPSAkUnVubmluZ1N0eWxlcw0KICAgICAgICAgICAgICAgICRDdXJybGluZS5jb250ZW50U2l6ZSA9IDANCiAgICAgICAgICAgICAgICAjIFdyaXRlLVZlcmJvc2UgIiokSW52b2sgfCBDdXJyIFRvdGFsIExpbmVzOiAkKCRjdXJybGluZS5maW5hbExpbmVzLkNvdW50KSINCiAgICAgICAgICAgIH0NCiAgICAgICAgfQ0KICAgICAgICAkQWxsQ2h1bmtzID0gJFRleHQgLXJlcGxhY2UgIigke0VzY2FwZUNvZGVTcGxpdHRlcn0pKyguKj8pKD89JHtFc2NhcGVDb2RlU3BsaXR0ZXJ9fCQpIiwiJCgkRGl2aWRlcnMuY2h1bmspYCQxJCgkRGl2aWRlcnMuc3R5bGUpYCQyIiAtc3BsaXQgJERpdmlkZXJzLmNodW5rDQogICAgICAgIGlmICgkQWxsQ2h1bmtzWzBdIC1ub3Rjb250YWlucyAkRGl2aWRlcnMuc3R5bGUpIHskQWxsQ2h1bmtzWzBdID0gIiQoJERpdmlkZXJzLnN0eWxlKSQoJEFsbENodW5rc1swXSkifSAjIFRoZSBmaXJzdCBjaHVuayBjb3VsZCBoYXZlIG5vIHN0eWxlcw0KICAgICAgICBmb3JlYWNoICgkQ3VyckNodW5rIGluICRBbGxDaHVua3MpIHsNCiAgICAgICAgICAgICRTdHlsZSwkVGV4dENodW5rID0gJEN1cnJDaHVuayAtc3BsaXQgJERpdmlkZXJzLnN0eWxlDQogICAgICAgICAgICAkUnVubmluZ1N0eWxlcyA9ID86ICRDb2xvckNvZGVzRGlzY3JldGVQZXJMaW5lICIkUnVubmluZ1N0eWxlcyRTdHlsZSIgJFN0eWxlDQogICAgICAgICAgICAjIFdyaXRlLUhvc3QgLWYgMiAoIkluY29taW5nU3R5bGU6ICRTdHlsZSB8IFJ1bm5pbmdTdHlsZXM6ICRSdW5uaW5nU3R5bGVzIiAtcmVwbGFjZSAoW3JlZ2V4XTo6RXNjYXBlKCQoR2V0LUVzY2FwZSkpKSwnXGUnKQ0KICAgICAgICAgICAgIyBXcml0ZS1Ib3N0IC1mIFllbGxvdyAiVGV4dENodW5rOiAkVGV4dENodW5rIg0KICAgICAgICAgICAgJEN1cnJsaW5lLnN0eWxlZERhdGEgKz0gJFJ1bm5pbmdTdHlsZXMNCiAgICAgICAgICAgICRUZXh0Q2h1bmtTdHJJbmRleCA9IDANCiAgICAgICAgICAgICMgV3JpdGUtVmVyYm9zZSAiKiRJbnZvayB8IFRleHRDaHVuazogJFRleHRDaHVuayB8IEFsbENodW5rc1NpemU6ICQoKCcnKyRBbGxDaHVua3MuTGVuZ3RoKS5QYWRMZWZ0KDMpKSINCiAgICAgICAgICAgIHdoaWxlKCRUZXh0Q2h1bmtTdHJJbmRleCAtbHQgJFRleHRDaHVuay5MZW5ndGgpIHsNCiAgICAgICAgICAgICAgICBpZiAoJGlzVmVyYm9zZSkge1BsYWNlLUJ1ZmZlcmVkQ29udGVudCAoIiRJbnZvayB8IExpbmVEYXRhOiAkKCgnJyskQ3VycmxpbmUuc3R5bGVkRGF0YS5MZW5ndGgpLlBhZExlZnQoMykpIHwgQ2h1bmtJZHg6ICQoKCcnKyRUZXh0Q2h1bmtTdHJJbmRleCkuUGFkTGVmdCgzKSkgfCBDaHVua0xlbjogJCgkVGV4dENodW5rLkxlbmd0aCkgfCBGaW5hbExpbmVzOiAkKCRDdXJybGluZS5maW5hbExpbmVzLkNvdW50KSIpIC14IDAgLXkgKFtDb25zb2xlXTo6QnVmZmVySGVpZ2h0IC0gMSkgWWVsbG93IERhcmtHcmF5fQ0KICAgICAgICAgICAgICAgICRDaHVua1NpemUgPSAkVGV4dENodW5rLkxlbmd0aCAtICRUZXh0Q2h1bmtTdHJJbmRleA0KICAgICAgICAgICAgICAgIFdyaXRlLVZlcmJvc2UgIipDaHVua1NpemU6ICRDaHVua1NpemUgfCAkKCRDdXJybGluZS5jb250ZW50U2l6ZSkgfCAkV2luU2l6ZSINCiAgICAgICAgICAgICAgICBpZiAoKCRDdXJybGluZS5jb250ZW50U2l6ZSskQ2h1bmtTaXplKSAtbHQgJFdpblNpemUpIHsNCiAgICAgICAgICAgICAgICAgICAgIyBJZiB0aGUgY3VycmVudCBjaHVuayBmaXRzIGluIHRoZSBjdXJyZW50IGxpbmUNCiAgICAgICAgICAgICAgICAgICAgJEN1cnJsaW5lLnN0eWxlZERhdGEgKz0gJFRleHRDaHVuay5TdWJzdHJpbmcoJFRleHRDaHVua1N0ckluZGV4KQ0KICAgICAgICAgICAgICAgICAgICAkQ3VycmxpbmUuY29udGVudFNpemUgKz0gJENodW5rU2l6ZQ0KICAgICAgICAgICAgICAgICAgICAkVGV4dENodW5rU3RySW5kZXggKz0gJENodW5rU2l6ZQ0KICAgICAgICAgICAgICAgICAgICBjb250aW51ZQ0KICAgICAgICAgICAgICAgIH0NCiAgICAgICAgICAgICAgICAjIElmIHRoZSBjdXJyZW50IGNodW5rIGRvZXNuJ3QgZml0IGluIHRoZSBjdXJyZW50IGxpbmUNCiAgICAgICAgICAgICAgICAkbmV3Q29udGVudCA9ICRUZXh0Q2h1bmsuU3Vic3RyaW5nKCRUZXh0Q2h1bmtTdHJJbmRleCwgJFdpblNpemUtJEN1cnJsaW5lLmNvbnRlbnRTaXplKQ0KICAgICAgICAgICAgICAgICRDdXJybGluZS5zdHlsZWREYXRhICs9ICRuZXdDb250ZW50DQogICAgICAgICAgICAgICAgJEN1cnJsaW5lLmNvbnRlbnRTaXplICs9ICRuZXdDb250ZW50Lmxlbmd0aA0KICAgICAgICAgICAgICAgICRUZXh0Q2h1bmtTdHJJbmRleCArPSAkbmV3Q29udGVudC5sZW5ndGgNCiAgICAgICAgICAgICAgICAmICRDdXJybGluZS5uZXh0DQogICAgICAgICAgICB9DQogICAgICAgIH0NCiAgICAgICAgaWYgKCRDdXJybGluZS5jb250ZW50U2l6ZSAtZ3QgMCkgew0KICAgICAgICAgICAgaWYgKCRDdXJybGluZS5jb250ZW50U2l6ZSl7DQogICAgICAgICAgICAgICAgQWxpZ24tVGV4dCAtQWxpZ24gJEFsaWduIC1UZXh0ICRDdXJybGluZS5zdHlsZWREYXRhIC1Db2xvckNvZGVzRGlzY3JldGVQZXJMaW5lOiRDb2xvckNvZGVzRGlzY3JldGVQZXJMaW5lIHwgPyB7JF99IHwgJSB7DQogICAgICAgICAgICAgICAgICAgICRDdXJybGluZS5maW5hbExpbmVzICs9ICwkXw0KICAgICAgICAgICAgICAgIH0NCiAgICAgICAgICAgIH0gZWxzZSB7DQogICAgICAgICAgICAgICAgJEN1cnJsaW5lLmZpbmFsTGluZXNbLTFdICs9ICRDdXJybGluZS5zdHlsZWREYXRhDQogICAgICAgICAgICB9DQogICAgICAgIH0NCiAgICAgICAgcmV0dXJuICYgJEZpbmFsRm9ybWF0dGVyICRDdXJybGluZS5maW5hbExpbmVzICRSdW5uaW5nU3R5bGVzDQogICAgICAgIHJldHVybiAkQ3VycmxpbmUuZmluYWxMaW5lcw0KICAgIH0NCn0KCmZ1bmN0aW9uIEludm9rZS1PclJldHVybiB7cGFyYW0oW1BhcmFtZXRlcihNYW5kYXRvcnk9JHRydWUsIFZhbHVlRnJvbVBpcGVsaW5lPSR0cnVlLCBQb3NpdGlvbj0wKV1bQWxsb3dOdWxsKCldJENvZGUsIFtQYXJhbWV0ZXIoVmFsdWVGcm9tUmVtYWluaW5nQXJndW1lbnRzPTEpXSRfX1Jlc3QsIFtTd2l0Y2hdJEFzUHJvY2Vzc0Jsb2NrKQ0KDQogICAgaWYgKCEoJENvZGUgLWlzIFtTY3JpcHRCbG9ja10pKSB7cmV0dXJuICRDb2RlfQ0KICAgIGlmICghJEFzUHJvY2Vzc0Jsb2NrKSB7cmV0dXJuICYgJENvZGUgQF9fUmVzdH0NCiAgICByZXR1cm4gJSAtcHJvY2VzcyAkQ29kZSAtSW5wdXRPYmplY3QgJF9fUmVzdA0KfQoKZnVuY3Rpb24gUGxhY2UtQnVmZmVyZWRDb250ZW50IHtwYXJhbSgkVGV4dCwgJHgsICR5LCBbQ29uc29sZUNvbG9yXSRGb3JlZ3JvdW5kQ29sb3I9W0NvbnNvbGVdOjpGb3JlZ3JvdW5kQ29sb3IsIFtDb25zb2xlQ29sb3JdJEJhY2tncm91bmRDb2xvcj1bQ29uc29sZV06OkJhY2tncm91bmRDb2xvcikNCg0KICAgIGlmICghJFRleHQpIHtyZXR1cm59DQogICAgJGNyZCA9IFtNYW5hZ2VtZW50LkF1dG9tYXRpb24uSG9zdC5Db29yZGluYXRlc106Om5ldygkeCwkeSkNCiAgICAkYiA9ICRIb3N0LlVJLlJhd1VJDQogICAgJGFyciA9ICRiLk5ld0J1ZmZlckNlbGxBcnJheShAKCRUZXh0KSwgJEZvcmVncm91bmRDb2xvciwgJEJhY2tncm91bmRDb2xvcikNCiAgICAkeCA9IFtDb25zb2xlXTo6QnVmZmVyV2lkdGgtMS0kVGV4dC5sZW5ndGgNCiAgICAkYi5TZXRCdWZmZXJDb250ZW50cygkY3JkLCAkYXJyKQ0KfQoKZnVuY3Rpb24gR2V0LVdoZXJlIHsNCiAgICBbQ21kbGV0QmluZGluZyhEZWZhdWx0UGFyYW1ldGVyU2V0TmFtZT0iTm9ybWFsIildDQogICAgcGFyYW0oDQogICAgICAgIFtQYXJhbWV0ZXIoTWFuZGF0b3J5PSR0cnVlLCBQb3NpdGlvbj0wKV1bc3RyaW5nXSRGaWxlLA0KICAgICAgICBbU3dpdGNoXSRBbGwsDQogICAgICAgIFtQYXJhbWV0ZXIoUGFyYW1ldGVyU2V0TmFtZT0nTm9ybWFsJyldW1BhcmFtZXRlcihQYXJhbWV0ZXJTZXROYW1lPSdTY2FuJyldW1N3aXRjaF0kTWFudWFsU2NhbiwNCiAgICAgICAgW1BhcmFtZXRlcihQYXJhbWV0ZXJTZXROYW1lPSdTY2FuJyldW1N3aXRjaF0kRGJnLA0KICAgICAgICBbUGFyYW1ldGVyKFBhcmFtZXRlclNldE5hbWU9J1NjYW4nKV1bc3RyaW5nXSRQYXRoVmFyID0gIlBBVEgiDQogICAgKQ0KICAgICRJc1ZlcmJvc2UgPSAkRGJnIC1vciAkUFNDbWRsZXQuTXlJbnZvY2F0aW9uLkJvdW5kUGFyYW1ldGVycy5WZXJib3NlIC1vciAkUFNDbWRsZXQuTXlJbnZvY2F0aW9uLkJvdW5kUGFyYW1ldGVycy5EZWJ1Zw0KICAgICRXaGVyZUJpbkV4aXN0cyA9IEdldC1Db21tYW5kICJ3aGVyZSIgLWVhIFNpbGVudGx5Q29udGludWUNCiAgICAkSXNVbml4ID0gJFBTVmVyc2lvblRhYmxlLlBsYXRmb3JtIC1lcSAiVW5peCINCiAgICBpZiAoJEZpbGUgLWVxICJ3aGVyZSIgLW9yICRGaWxlIC1lcSAid2hlcmUuZXhlIikge3JldHVybiAkV2hlcmVCaW5FeGlzdHN9DQogICAgaWYgKCRXaGVyZUJpbkV4aXN0cyAtYW5kICEkTWFudWFsU2Nhbikgew0KICAgICAgICAkT3V0PSRudWxsDQogICAgICAgIGlmICgkSXNVbml4KSB7DQogICAgICAgICAgICAkT3V0ID0gd2hpY2ggJGZpbGUgMj4kbnVsbA0KICAgICAgICB9IGVsc2UgeyRPdXQgPSB3aGVyZS5leGUgJGZpbGUgMj4kbnVsbH0NCg0KICAgICAgICBpZiAoISRPdXQpIHtyZXR1cm59DQogICAgICAgIGlmICgkQWxsKSB7cmV0dXJuICRPdXR9DQogICAgICAgIHJldHVybiBAKCRPdXQpWzBdDQogICAgfQ0KICAgIGZvcmVhY2ggKCRGb2xkZXIgaW4gKEdldC1QYXRoIC1QYXRoVmFyICRQYXRoVmFyKSkgew0KICAgICAgICBpZiAoJElzVW5peCkgew0KICAgICAgICAgICAgJExvb2t1cCA9ICIkRm9sZGVyLyRGaWxlIg0KICAgICAgICAgICAgaWYgKCRJc1ZlcmJvc2UpIHtXcml0ZS1BUCAiKkNoZWNraW5nIFskTG9va3VwXSJ9DQogICAgICAgICAgICBpZiAoIShUZXN0LVBhdGggLVBhdGhUeXBlIExlYWYgJExvb2t1cCkpIHtjb250aW51ZX0NCiAgICAgICAgICAgIFJlc29sdmUtUGF0aCAkTG9va3VwIHwgJSBQYXRoDQogICAgICAgICAgICBpZiAoISRBbGwpIHtyZXR1cm59DQogICAgICAgIH0gZWxzZSB7DQogICAgICAgICAgICBmb3JlYWNoICgkRXh0ZW5zaW9uIGluIChHZXQtUGF0aCAtUGF0aFZhciBQQVRIRVhUKSkgew0KICAgICAgICAgICAgICAgICRMb29rdXAgPSAiJEZvbGRlci8kRmlsZSRFeHRlbnNpb24iDQogICAgICAgICAgICAgICAgaWYgKCRJc1ZlcmJvc2UpIHtXcml0ZS1BUCAiKkNoZWNraW5nIFskTG9va3VwXSJ9DQogICAgICAgICAgICAgICAgaWYgKCEoVGVzdC1QYXRoIC1QYXRoVHlwZSBMZWFmICRMb29rdXApKSB7Y29udGludWV9DQogICAgICAgICAgICAgICAgUmVzb2x2ZS1QYXRoICRMb29rdXAgfCAlIFBhdGgNCiAgICAgICAgICAgICAgICBpZiAoISRBbGwpIHtyZXR1cm59DQogICAgICAgICAgICB9DQogICAgICAgIH0NCiAgICB9DQp9CgpmdW5jdGlvbiBUZXN0LUFkbWluaXN0cmF0b3Igew0KICAgIGlmICgkUFNWZXJzaW9uVGFibGUuUGxhdGZvcm0gLWVxICJVbml4Iikgew0KICAgICAgICBpZiAoJCh3aG9hbWkpIC1lcSAicm9vdCIpIHsNCiAgICAgICAgICAgIHJldHVybiAkdHJ1ZQ0KICAgICAgICB9DQogICAgICAgIGVsc2Ugew0KICAgICAgICAgICAgcmV0dXJuICRmYWxzZQ0KICAgICAgICB9DQogICAgfQ0KICAgICMgV2luZG93cw0KICAgIChOZXctT2JqZWN0IFNlY3VyaXR5LlByaW5jaXBhbC5XaW5kb3dzUHJpbmNpcGFsIChbU2VjdXJpdHkuUHJpbmNpcGFsLldpbmRvd3NJZGVudGl0eV06OkdldEN1cnJlbnQoKSkpLklzSW5Sb2xlKFtTZWN1cml0eS5QcmluY2lwYWwuV2luZG93c0J1aWx0aW5Sb2xlXTo6QWRtaW5pc3RyYXRvcikNCn0KClNldC1BbGlhcyBjb2wgR2V0LUNvbG9yClNldC1BbGlhcyA/OiBJbnZva2UtVGVybmFyeQpTZXQtQWxpYXMgd2hpY2ggR2V0LVdoZXJl")
} elseif($AP_CONSOLE.warnOnCompileRun) {& $AP_CONSOLE.warnOnCompileRun}
# ========================================END=OF=COMPILER=================================================================|
$Dbg = $Dbg -or $PSBoundParameters.ContainsKey('Verbose') -or $PSBoundParameters.ContainsKey('Debug')
$Ver = "1.6 (APC: $($AP_CONSOLE.version))"

# Track all AP-Console Commands
if (!$AP_CONSOLE -or !$AP_CONSOLE.functions) {
    Write-APL "!","AP-Console not loaded, only a valid AP-Console session can run this command. Alternatively, define all the functions you'd like to support in ","+`$AP_CONSOLE.functions"
    exit 1
}
if (!$AP_CONSOLE.Version -or $AP_CONSOLE.Version -lt 1.2) {
    Write-APL "!","AP-Console Version is too old, please update to at least 1.2 to use this command"
    exit 1
}
function Get-AllNestedFunctionalDeps ([System.Management.Automation.Language.Ast]$RootAst, [System.Management.Automation.Language.Token[]]$Tokens, $Depth = 0, $SeenFuncs = @{}) {
    if (!$RootAst) {return}
    $ClassRefs = $RootAst.findAll({$args[0] -is [System.Management.Automation.Language.TypeDefinitionAst]}, $true) | Group-Object name | % Group | select -f 1 | ? {
        $AP_CONSOLE.classes.Contains($_.Name) -and !$SeenClassDefs.$_.Name
    } | % {
        $SeenClassDefs.($_.Name) = $_.Extent.Text # Store the class definition
    }
    ScanFor-ForcedCommands -Tokens $Tokens
    $DefinedFuncs = $RootAst.findAll({$args[0] -is [System.Management.Automation.Language.FunctionDefinitionAst]}, $true) | % name | select -Unique
    $Commands = $RootAst.findAll({$args[0] -is [System.Management.Automation.Language.CommandAst]}, $true) | % {$_.CommandElements[0]} | % value | select -Unique | % {
        # Ignore if it's not a known AP-Function / Alias or is one of the defined functions in the file
        if ((!$TmpHash.$_ -and $_ -notin $Aliases) -or $SeenFuncs.$_ -or ($_ -in $DefinedFuncs)) {return}
        $SeenFuncs.$_++
        $Name = $_
        $Cmd = Get-Command $_ -ea SilentlyContinue
        if ($Cmd.ResolvedCommandName) {
            [PSCustomObject]@{
                Name = $_
                Depth = $Depth
                Type = "Alias"
            }
            $SeenFuncs.$Name++
            $Name = $Cmd.ResolvedCommandName
            $Cmd = Get-Command $Name -ea SilentlyContinue
        }
        $Ast = $Cmd.ScriptBlock.Ast
        $SubTokens = @()
        if (!$Ast) {return}
        [void][System.Management.Automation.Language.Parser]::ParseInput($Cmd.ScriptBlock.ToString(), [ref]$SubTokens, [ref]$null)
        return @([PSCustomObject]@{
            Name = $Name
            Depth = $Depth
            Type = "Function"
        })+(Get-AllNestedFunctionalDeps $Ast $SubTokens -Depth ($Depth + 1) -SeenFuncs $SeenFuncs)
    }

    return Flatten $Commands | ? {$_} | Sort-Object # To make sure the base64 code is deterministic
}

function Write-CompiledFile ($Data) {
    if ($OverwriteSrc) {
        $OutputFolder = Split-Path $File
    }
    if ((Split-Path $File) -eq $OutputFolder -and !$OverwriteSrc) {
        $Outfile = "$((Split-Path -leaf $File).replace('.ps1','-Compiled.ps1'))"
    } else {
        $Outfile = "$(Split-Path -leaf $File)"
    }
    $enc = JS-OR {
        $e = Get-FileEncoding $File
        if ($e -in "utf32","unicode","bigendianunicode") {""} else {[System.Text.Encoding]::$e}
    } "unicode"
    $Verb = ?: $Strip "Unc" "C"
    Write-APL ">+","${Verb}ompiled [","+$OutFile","] with Encoding [","+$(JS-OR $Enc.EncodingName $Enc)","] in Folder [","*$OutputFolder","]"
    $Data | Out-File -Encoding $Enc "$OutputFolder\$OutFile"
}

function Remove-OldInjecter ($Data) {
    $ReplaceExpr = "(?s)\# ?=+START=OF=COMPILER=+\|`n.+\# ?=+END=OF=COMPILER=+\|"
    return $Data -replace "$ReplaceExpr`n|`n$ReplaceExpr",""
}
function ScanFor-ForcedCommands {
    param([System.Management.Automation.Language.Token[]]$Tokens)
    # Scan for forced required functions
    # Example: ap-compiler: Write-APL,AP-Require
    $tokens | ? kind -eq 'comment' | ? text -Match "^\s*..?\s*ap-compiler?\:" | % {$_ -replace "^\s*..?\s*ap-compiler?\: *(.+?) *(?<a>\#\>)?$",'$1' -split ","} | % {$_.Trim()} | ? {$_} | % {
        Write-APL ">#","@AP-Compiler Forced Command: ","+$_"
        if ($_ -notin $TmpHash.Keys -and $_ -notin $Aliases) {Throw "Invalid AP-Compiler Forced Command [$_]";exit 1}
        $script:ForcedDependencies += ,$_
    }
}

# Build a minimal "thin shim" for a specific scriptblock ? used to inject AP Console
# dependencies into argument-completer scriptblocks, which PowerShell evaluates in
# a fresh scope at tab-completion time and therefore can't see the script-scope
# functions defined by the main compiler block.
#
# Returns the shim text (comment + one-line base64 iex) or $null if the scriptblock
# doesn't call any AP Console functions and therefore needs nothing.
function Build-ThinShim {
    param([System.Management.Automation.Language.ScriptBlockAst]$SbAst)
    # Get-AllNestedFunctionalDeps mutates $script:ForcedDependencies and $Script:SeenClassDefs.
    # Snapshot and restore so a thin-shim scan doesn't pollute the main compiler block.
    $savedForced = $script:ForcedDependencies
    $savedSeenClasses = $Script:SeenClassDefs.Clone()
    $script:ForcedDependencies = @()
    try {
        $sbTokens = @()
        [void][System.Management.Automation.Language.Parser]::ParseInput($SbAst.ToString(), [ref]$sbTokens, [ref]$null)
        # Fresh $SeenFuncs so we capture THIS scriptblock's deps (the parent's call
        # already filled the global $SeenFuncs with the whole script's deps).
        $deps = @(Get-AllNestedFunctionalDeps $SbAst $sbTokens -SeenFuncs @{})
        if (!$deps) {return $null}

        $need2Import = @{}
        $need2ImportAL = @{}
        $deps | % {
            $name = $_.Name -replace '^\w+\:(\S+)$','$1'
            if ($_.Type -eq 'Function') {$need2Import.$name++}
            elseif ($name -ne 'Item') {
                $need2ImportAL.$name++
                $need2Import.((Get-Alias $name).Definition)++
            }
        }
        $finalSet = @($need2Import.Keys) | Sort-Object
        $finalAlSet = @($need2ImportAL.Keys) | Sort-Object -Unique
        $code = $finalSet | % {"function $_ {1}{0}{2}" -f (iex "`${Function:$_}"),'{',"}`n"}
        $code += $finalAlSet | % {"Set-Alias $_ {0}" -f ((Get-Alias $_).Definition)}
        if (!$code) {return $null}

        $b64 = Convert-ToBase64 ($code -join "`n")
        return "# AP Console compile thin shim`n& (Get-Alias iex) ([System.Text.Encoding]::UTF8.GetString([Convert]::FromBase64String(""$b64"")))`n"
    } finally {
        $script:ForcedDependencies = $savedForced
        $Script:SeenClassDefs = $savedSeenClasses
    }
}

# Regex that matches a previously-injected thin shim (comment + the iex line).
# Used both for stripping on re-compile and during -Strip (uncompile).
$Script:ThinShimPattern = "(?m)^[ \t]*# AP Console compile thin shim[^\n]*\n[ \t]*& \(Get-Alias iex\)[^\n]*\n"

$TmpHash = @{}
$AP_CONSOLE.functions | % {$TmpHash.$_ = $_}
$Aliases = Get-Alias | ? {$TmpHash.($_.Definition)} | % {"$_"}

# Validation
if (!$File -or !(Test-Path -type Leaf $File)) {Throw "Invalid File [$File]";exit}
if (!(Test-Path -type Container $OutputFolder)) {Throw "Invalid Folder [$OutputFolder]";exit}
if ($File -notmatch ".\.ps1$") {Throw "Invalid File Type [$File], expected *.ps1";exit}
$File = (Get-Item $File).FullName
$OutputFolder = (Get-Item $OutputFolder).FullName

if ($Strip) {
    Write-APL "*","Uncompiling File [","+$File","]"
    $OverwriteSrc = $true
    $OData = $Data = [IO.File]::ReadAllText($File)
    $Data = Remove-OldInjecter $Data
    # Also strip thin shims injected into argument-completer scriptblocks.
    $Data = $Data -replace $Script:ThinShimPattern, ""
    if ($OData -eq $Data) {
        Write-APL ">!","No Compiler Code Found, File is already uncompiled!"
        exit 0
    }
    Write-APL ">+","Uncompiled File!"
    $Data = $Data -replace "(?s)\# ?=+START=OF=COMPILER=+\|`n.+\# ?=+END=OF=COMPILER=+\|",""
    Write-CompiledFile $Data
    exit 0
}

# Let's process the file
$Data = [IO.File]::ReadAllLines($File)
$Script:Need2Import = @{}
$Script:Need2ImportAL = @{}
$Script:BlackListFunctions = @{"IN-Code-Debug-Console"=1;"Get-APIKey"=1;"Get-GMAIL"=1;"Backup"=1}
Write-APL "*","Compiling ","+$(Split-Path -leaf $File):"

# Use AST to detect the functions used in this script
$Tokens = @() # Where the comments will be scannable
$Script:ASTT = [System.Management.Automation.Language.Parser]::ParseFile($File, [ref]$Tokens, [ref]$null)
$Script:SeenClassDefs = @{}
$script:ForcedDependencies = @()
$Script:Functions = @(Get-AllNestedFunctionalDeps $Script:ASTT $Tokens)

$ForcedFakeExpr = "{$($script:ForcedDependencies -join ";")}"
$ForcedFakeAst = [System.Management.Automation.Language.Parser]::ParseInput($ForcedFakeExpr, [ref]$Tokens, [ref]$null)
$Script:Functions += Get-AllNestedFunctionalDeps $ForcedFakeAst $Tokens

if ($Dbg) {
    Write-APL ">*","Globally detected functions:"
    $MaxNameSize = [math]::Max(($Script:Functions | % {$_.Name.Length} | Measure-Object -Maximum).Maximum, ($SeenClassDefs.Keys | % Length | Measure-Object -Maximum).Maximum)+3
    $MaxNameSize = [math]::Clamp($MaxNameSize, 23, [Math]::Max(24, [Console]::WindowWidth * .5))
    $Script:Functions | % {
        Write-APL ">>#","+$($_.Name) ","#$("." * [Math]::max(0, $MaxNameSize - $_.Name.length)) ","@$($_.Type.PadLeft(8))","# | Depth: ","@$($_.Depth)"
    }
    $SeenClassDefs.Keys | % {
        Write-APL ">>#","+$($_) ","#$("." * [Math]::max(0, $MaxNameSize - $_.length)) ","@$("Class".PadLeft(8))","# | Depth: ","@0"
    }
}
$Script:Functions | % {
    $Name = $_.Name
    $Type = $_.Type
    $Name = $Name -replace "^\w+\:(\S+)$",'$1'
    if ($Type -eq "Function") {
        $Script:Need2Import.$Name++
    } else {
        if ($Name -eq "Item") {return}
        $Script:Need2ImportAL.$Name++
        $Need2Import.((Get-Alias $Name).Definition)++
    }
}

$FinalSet = @($Need2Import.Keys) | ? {!$OtroFunc.$_}
$FinalAlSet = @($Need2ImportAL.Keys) | select -unique
$Code = $FinalSet | % {"function $_ {1}{0}{2}" -f $(if ($BlackListFunctions.$_) {"Write-Host -f yellow '[AP-COMPILER] Module [$_] disabled for this program'"} else {iex "`${Function:$_}"}),"{","}`n"}
$Code += $FinalAlSet | % {"Set-Alias $_ {0}" -f ((Get-Alias $_).Definition)}
$Code += $SeenClassDefs.Values
if ($Code) {
    if ($FinalSet -and !$Dbg)            {Write-APL ">*","@Adding Functions $(Print-List $FinalSet)"}
    if ($FinalALSet -and !$Dbg)          {Write-APL ">*","@Adding Aliases   $(Print-List $FinalALSet)"}
    if ($SeenClassDefs.Count -and !$Dbg) {Write-APL ">*","@Adding Classes   $(Print-List $SeenClassDefs.Keys)"}
    $Injecter = @(
        ""
        "# =======================================START=OF=COMPILER================================================================|"
        "#    The Following Code was added by AP-Compiler $Ver To Make this program independent of AP-Core Engine"
        "#    GitHub: https://github.com/avdaredevil/AP-Compiler"
        "# ========================================================================================================================|"
        '$Script:PSHell=$(if($PSHell){$PSHell}elseif($PSScriptRoot){$PSScriptRoot}else{"."});'
        "if(`$AP_CONSOLE.mode -ne 'main' -or `$AP_CONSOLE.customFlags.runAsCompiled) {"
        "    `$Script:AP_CONSOLE = [PsCustomObject]@{version=[version]'$($AP_CONSOLE.Version)'; mode = 'shim'; customFlags = @{}}"
        "    function B64 {$("${Function:Convert-FromBase64}".trim() -replace "(`r?`n){2,}"," ")}"
        "    # This syntax is to prevent AV's from misclassifying this as anything but innocuous"
        "    & (Get-Alias iex) (B64 ""$(Convert-ToBase64 ($Code -join "`n"))"")"
        "} elseif(`$AP_CONSOLE.warnOnCompileRun) {& `$AP_CONSOLE.warnOnCompileRun}"
        "# ========================================END=OF=COMPILER=================================================================|"
    ) -join "`n"
}
$Data = $Data -join "`n"
$NewCode = Remove-OldInjecter $Data
if ($NewCode -ne $Data) {
    Write-APL ">!","Old Compiler Code Detected... Removing..."
    $Data = $NewCode
}

# Also strip any previously-injected thin shims so re-compile doesn't duplicate them.
$stripped = $Data -replace $Script:ThinShimPattern, ""
if ($stripped -ne $Data) {
    Write-APL ">!","Old Thin-Shim Code Detected... Removing..."
    $Data = $stripped
}

# --- Argument-completer thin-shim injection ---
# Argument-completer scriptblocks (both `Register-ArgumentCompleter -ScriptBlock {...}`
# and `[ArgumentCompleter({...})]` parameter attributes) run in a FRESH scope at
# tab-completion time. They don't see the script-scope functions the main compiler
# block defines, so a call to e.g. `Do-ArgMatch` inside a completer breaks in a
# compiled script. Fix: inject a minimal self-contained shim at the top of each
# completer scriptblock with just the deps that scriptblock actually uses.
#
# Parse $Data (not $File) so AST offsets align with the current string ? the main
# AST came from ParseFile and its offsets count \r\n as 2 chars, which won't match
# $Data's normalized \n-only line endings.
$astForPositions = [System.Management.Automation.Language.Parser]::ParseInput($Data, [ref]$null, [ref]$null)
$completerSbs = [System.Collections.Generic.List[object]]::new()
# Form 1: `Register-ArgumentCompleter -ScriptBlock {...}`
$astForPositions.FindAll({
    $a = $args[0]
    ($a -is [System.Management.Automation.Language.CommandAst]) -and
    $a.CommandElements -and
    ($a.CommandElements[0] -is [System.Management.Automation.Language.StringConstantExpressionAst]) -and
    ($a.CommandElements[0].Value -eq 'Register-ArgumentCompleter')
}, $true) | % {
    $sb = $_.CommandElements | ? {$_ -is [System.Management.Automation.Language.ScriptBlockExpressionAst]} | select -First 1
    if ($sb) {$completerSbs.Add($sb)}
}
# Form 2: `[ArgumentCompleter({...})]` parameter attribute
$astForPositions.FindAll({
    $a = $args[0]
    ($a -is [System.Management.Automation.Language.AttributeAst]) -and
    ($a.TypeName.Name -in @('ArgumentCompleter','ArgumentCompleterAttribute'))
}, $true) | % {
    $sb = $_.PositionalArguments | ? {$_ -is [System.Management.Automation.Language.ScriptBlockExpressionAst]} | select -First 1
    if ($sb) {$completerSbs.Add($sb)}
}
if ($completerSbs) {
    $thinInsertions = @()
    foreach ($sbArg in $completerSbs) {
        $sbAst = $sbArg.ScriptBlock
        $shimText = Build-ThinShim $sbAst
        if (!$shimText) {continue}
        # Insert after `param(...)` if the completer has one (param must be the first
        # statement in a scriptblock), else right after the opening `{`.
        $insertOffset = $sbAst.Extent.StartOffset + 1
        if ($sbAst.ParamBlock) {$insertOffset = $sbAst.ParamBlock.Extent.EndOffset}
        $thinInsertions += ,@{offset = $insertOffset; text = "`n$shimText"}
    }
    if ($thinInsertions) {
        Write-APL ">*","@Injecting thin shims into $($thinInsertions.Count) argument completer scriptblock(s)"
        # Apply in reverse-offset order so each insertion doesn't invalidate the
        # offsets of earlier (lower-offset) ones.
        $thinInsertions | Sort-Object {-[int]$_.offset} | % {
            $Data = $Data.Insert($_.offset, $_.text)
        }
    }
}

if (!$Injecter) {
    Write-APL ">*","No Functions or Aliases to add... Writing the file as is..."
} elseif ($Data -match "`n?\[CmdletBinding\(\)\] *`n" -and !$ForceLinearLayout) {
    Write-APL ">*","Detected Procedural Layout"
    $M = [Regex]::Match($Data,"(?i)(Begin|Process|End) *\{")
    if (!$M.success) {
        Write-APL ">>!","No Begin/Process/End Tags found... Please check that your code is runnable?"
        Write-APL ">>!","If you are sure it works, use ","!-ForceLinearLayout"," switch to force linear layout"
        exit 1
    } else {
        $Data = $Data.insert($M.Index+$M.Length,$Injecter)
    }
} else {
    Write-APL ">*","Detected Linear Layout",$(if($ForceLinearLayout){"! (Forced)"}else{""})
    $M = [Regex]::Match($Data,"(?i)(`n|^)param *\(")
    if (!$M.success) {$Data = "$("$Injecter`n".TrimStart())$Data"} else {
        $i = 1;$dex=0;$InString=0
        foreach ($c in $Data[($M.Index+$M.Length)..$Data.Length]) {$dex++
            if ($Dbg) {Write-APL ">>*","Explored $c [Stack: $i |$Dex :: $InString -> $(('Code','Dbl-Quot','Single-Quot')[$InString])]"}
            if ($InString -ne 2 -and $c -eq """") {$InString=(1,0)[$InString]}
            elseif ($InString -ne 1 -and $c -eq "'") {$InString=(2,-1,0)[$InString]}
            elseif ($InString) {continue}
            if ($c -eq "(") {$i++}
            elseif ($c -eq ")") {if (!(--$i)) {break}}
        }
        $Data = $Data.insert($M.Index+$M.Length+$dex,$Injecter)
    }
}
Write-CompiledFile $Data
if ($PassThru) {return $code}
